### ISSUE TITLE
DoGe no longer detect props in JSX arrow function if there is no default value

### ISSUE THREAD

**Issue by s-u-d-o-e-r** [kkoomen/vim-doge#100]
A few months ago DoGe automatically detected props, but now it just generates 1 prop comment

NVIM v0.5.0-59712f6
Build type: Release

Without default value:
<img width="852" alt="Screenshot 2020-10-02 at 13 09 51" src="https://user-images.githubusercontent.com/29402490/94912728-c58c6600-04b0-11eb-9507-99b5b8f6505b.png">
With default value:
<img width="663" alt="Screenshot 2020-10-02 at 14 27 57" src="https://user-images.githubusercontent.com/29402490/94918562-7e57a280-04bb-11eb-8f5e-b7acce3e003b.png">

**Comment by kkoomen** [comment]
I'm currently doing a rewrite to use tree-sitter as a parser where this problem is already fixed. Please be patient and wait for our new release v3 where this will be fixed.

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v3.0.0](https://github.com/kkoomen/vim-doge/tree/v3.0.0).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
