### ISSUE TITLE
Question about colorscheme

### ISSUE THREAD

**Issue by Shatur95** [kkoomen/vim-doge#102]
Hi! Thank you for the awesome plugin!
What colorscheme did you use in [this](https://asciinema.org/a/PXtgawXXnDOVbAm6Kk4cS2MmC) video? I liked it very much, but I can't find a similar one :)

**Comment by kkoomen** [comment]
@Shatur95 I do use my own custom colorscheme, but I did use [onedark](https://github.com/joshdick/onedark.vim) and then customized it [like so](https://github.com/kkoomen/dotfiles-osx/blob/master/.vimrc#L592-L620).

**Comment by Shatur95** [comment]
Thank you!
