### ISSUE TITLE
Typescript parser failed but generation still works

### ISSUE THREAD

**Issue by TaylorBeeston** [kkoomen/vim-doge#105]
**Describe the bug**
After updating to v3, whenever I run vim doge in a javascript file, I get multiple "Typescript parser failed" messages, but the generation still works.

**Settings**
default

**To Reproduce**

See https://asciinema.org/a/pR1pmQowa565LioiqDH4cvZQ5

**Expected behavior**
Everything to be the same minus the "Typescript parser failed" warnings

**Screenshots**
[Asciinema](https://asciinema.org/a/pR1pmQowa565LioiqDH4cvZQ5) (Please ignore the gql server warnings when opening the file, those are unrelated)

![neofetch](https://user-images.githubusercontent.com/39720479/95681978-b59f1100-0b97-11eb-8b73-7591923c3a70.png)

**Out of `vim --version`**
```bash
❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by kkoomen** [comment]
Well, at least it still works ¯\_(ツ)_/¯

Thanks for reporting. I'll have a look at it ASAP.

**Comment by TaylorBeeston** [comment]
Appreciate it!
