### ISSUE TITLE
Not sure why it doesn't work

### ISSUE THREAD

**Issue by drselump14** [kkoomen/vim-doge#107]
After installing the plugin and invoke `:call doge#install()` , invoking `:DogeGenerate` or  `<leader>d` does not produce anything. Did  I miss something? Any help would be appreciated

**Comment by kkoomen** [comment]
@drselump14 Can you please post the output of the following commands:

- `vim --version`
- `npm --version`
- `node --version`

**Comment by drselump14** [comment]
Hi @kkoomen , thanks for the support!

```
❯ nvim --version
Alias tip: vi --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info


❯ npm --version
6.14.5


❯ node --version
v11.14.0
```

I've installed it using Plug

`Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }`

Any hint?

**Comment by s-u-d-o-e-r** [comment]
I have the same issue

**Comment by kkoomen** [comment]
@drselump14 @s-u-d-o-e-r I just did a clean install with node v11.15.0 from master and both nvim and neovim have no problems for me if I use this javascript example (I even have a fresh catalina install since yesterday), both `<Leader>d` and `:DogeGenerate` have no problem:

Input: `test.js`:

```js
function foo(p1, p2) {}
```

output:

```js
/**
 * [TODO:description]
 *
 * @param {[TODO:type]} p1 - [TODO:description]
 * @param {[TODO:type]} p2 - [TODO:description]
 * @return {[TODO:type]} [TODO:description]
 */
function foo(p1, p2) {}
```

Can at least one of you guys answer the following:
- What's the input that you've used that doesn't trigger the expected documentation? For example, if you didn't get any results with a certain javascript expression then please provide me with this
- What's the output of: `ls -l path/to/vim-doge/node_modules | grep -i tree-sitter` ?
- Did you use `g:doge_parsers` to limit the amount of parsers?
- Inside `autoload/doge/helpers.vim` at line 92 add a new line with `echo 'result -> ' . string(l:result)`, open a new file with the example I added above (the one I mentioned that worked for me) and trigger vim-doge and paste the output.

**Comment by s-u-d-o-e-r** [comment]
@kkoomen 
_What's the output of: ls -l /path/to/your/local/vim-doge/node_modules | grep -i tree-sitter ? (Please provide me with the path as well where your local vim-doge folder is located)_

**nothing**

_Did you use g:doge_parsers to limit the amount of parsers?_

**no**

_What's the input that you've used that doesn't trigger the expected documentation? For example, if you didn't get any results with a certain javascript expression then please provide me with this_

**nothing happens even with your example**


I even have tried to install tree-sitter in vim-doge folder manually:

``` npm i tree-sitter

> husky@4.2.5 install /Users/nazar/.vim/plugged/vim-doge/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> tree-sitter@0.17.0 install /Users/nazar/.vim/plugged/vim-doge/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.0 runtime=node arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nazar/.vim/plugged/vim-doge/node_modules/tree-sitter
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.17.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.17.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by s-u-d-o-e-r** [comment]
i think that this error is the reason why it doesn't work

**Comment by kkoomen** [comment]
@s-u-d-o-e-r I've had that error as well. Reinstall xcode and everything should be fine.

@drselump14 Can you confirm the error in [this](https://github.com/kkoomen/vim-doge/issues/107#issuecomment-707088736) comment? Do you have the same when running `npm i tree-sitter` in the vim-doge folder manually?

**Comment by s-u-d-o-e-r** [comment]
@kkoomen  
i fixed this error with - sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
and then :call doge#install()

my result:
after :DogeGenerate -
![image](https://user-images.githubusercontent.com/29402490/95747316-ef0f7380-0ca0-11eb-9d3a-978fd3d88247.png)

after pressing Enter -

![image](https://user-images.githubusercontent.com/29402490/95747364-fc2c6280-0ca0-11eb-9bbd-f18b8b53a463.png)

**Comment by kkoomen** [comment]
This has just been fixed, see #105

**Comment by drselump14** [comment]
OK,  it works. Thanks

In my case, to install `tree-sitter` I have to switch libtool from homebrew version to mac version.
Using homebrew version of libtool will raise exception when installing `tree-sitter`

**Comment by kkoomen** [comment]
>  Using homebrew version of libtool will raise exception when installing tree-sitter

@drselump14 I'm trying to use [`pkg`](https://npmjs.com/package/pkg) to bundle everything together to remove the npm + node prerequisites and possibly these kind of errors as well.

**Comment by joehannes** [comment]
got this same problem here.
Mac Silicon M1 on MacOs Monterey ...
After bumping tree-sitter version to 0.20.0 in package.json of the installed plugin I can `npm i tree-sitter` successfully, yet `:DogeGenerate jsdoc` still doing nothing

**Comment by dotsinspace** [comment]
It doesn't work. Any other plugin that can do the same ?
