### ISSUE TITLE
JSX props still don’t work even with DoGe v3 

### ISSUE THREAD

**Issue by s-u-d-o-e-r** [kkoomen/vim-doge#109]
Don't work even with the default value setted

Issue Related to the #100

![Screenshot 2020-10-12 at 15 54 58](https://user-images.githubusercontent.com/29402490/95748817-49113880-0ca3-11eb-87fb-d64def4eaf2d.png)
![Screenshot 2020-10-12 at 15 55 15](https://user-images.githubusercontent.com/29402490/95748840-53333700-0ca3-11eb-8c35-af24172859ac.png)

**Comment by kkoomen** [comment]
This is expected behavior, because you only have 1 argument. Do you want a `@param` tag for each parameter?

**Comment by s-u-d-o-e-r** [comment]
@kkoomen  yes, it would be nice because this is a must-have for React development and I use this every day)

**Comment by kkoomen** [comment]
@s-u-d-o-e-r I've been using React for years and never needed it, because as I said, a bit too much for me personally, *but* I do understand why people would have it. I'll add it tomorrow evening as a configurable option and I'll turn it on by default. If people find it annoying then they can turn it off. 

I'll post another comment tomorrow with the new integrated option.

**Comment by s-u-d-o-e-r** [comment]
@kkoomen ❤️❤️❤️

**Comment by kkoomen** [comment]
This feature has been merged and released in [v3.1.0](https://github.com/kkoomen/vim-doge/tree/v3.1.0). See [the new option](https://github.com/kkoomen/vim-doge/tree/v3.1.0#javascript) if you want to change this behavior.

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by s-u-d-o-e-r** [comment]
@kkoomen  are you sure that it works?

and yes, I updated the package

works same for 
```
let g:doge_javascript_settings = {
\  'destructuring_props': 1,
\}
```
and 
```
let g:doge_javascript_settings = {
\  'destructuring_props': 0,
\}
```

![image](https://user-images.githubusercontent.com/29402490/96086592-3c6f2900-0ecb-11eb-9316-12a85871fc34.png)

![Screenshot 2020-10-15 at 09 45 39](https://user-images.githubusercontent.com/29402490/96086556-311bfd80-0ecb-11eb-9475-d3ba16d0a844.png)

**Comment by kkoomen** [comment]
When you pull, you have to run `npm run build` inside the vim-doge folder. If you use `Plug` aka vim-plug then this shouldn't be an issue.

**Comment by s-u-d-o-e-r** [comment]
Hmm, I installed via vim-plug but after update, I had this issue, npm run build helped me, strange

**Comment by s-u-d-o-e-r** [comment]
Ohh..., I love this feature, you are the best

**Comment by kkoomen** [comment]
> Hmm, I installed via vim-plug but after update, I had this issue, npm run build helped me, strange

It should re-run the `do` inside vim-plug when running `:PlugUpdate`
