### ISSUE TITLE
Linux: tree_sitter_runtime_binding.node: invalid ELF header

### ISSUE THREAD

**Issue by promisedlandt** [kkoomen/vim-doge#112]
**Describe the bug**

On Linux, I'm getting the the following stacktrace:

```
pkg/prelude/bootstrap.js:1611
        const res = ancestor.dlopen.apply(process, args);
                                    ^

Error: /tmp/649c1087bb4327f1e495a2c3524fd9e1c76d3b9998812ff9ba72cce58b3fd580_tree_sitter_runtime_binding.node: invalid ELF header
    at tryImporting (pkg/prelude/bootstrap.js:1611:37)
    at process.dlopen (pkg/prelude/bootstrap.js:1637:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1248:18)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1229:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.8460 (/snapshot/vim-doge/build/index.js)
    at __webpack_require__ (/snapshot/vim-doge/build/index.js)
```

This also happens when I execute the binary completely without vim, i.e. `./bin/vim-doge`.
I was able to reproduce it in a Ubuntu 20.04 VM, so I'm guessing it's a build problem, not my system.

Only similar issue I could find is https://github.com/georgewfraser/vscode-tree-sitter/issues/3 but I don't know anything about TS at all.

As this seems like a non-vim related issue I have omitted the other bug report headings.

**Versions**

- vim-doge 3.2.9 from https://github.com/kkoomen/vim-doge/releases/download/3.2.9/vim-doge-linux
- Debian bullseye/sid / Ubuntu 20.04

**Comment by kkoomen** [comment]
It's definitely an issue with [`pkg`](https://github.com/vercel/pkg) itself and [vercel/pkg#665](https://github.com/vercel/pkg/issues/665) could be related. I'll have a look at it later.

**Comment by sh0w98** [comment]
Facing the same issue right now. Reverted back to a manual install of 3.1.1 for a working install. Running Arch Linux (linux 5.9.1.arch1-1 kernel).

**Comment by jerri** [comment]
Problem persists with new version 3.3.1 unfortunately!

**Comment by kkoomen** [comment]
So the problem here is that I did ship a linux binary, but because I did run `npm install` on my Mac, it did build tree_sitter for mac and those `.node` files are being put into the final binary.

I did make a [question](https://www.reddit.com/r/node/comments/jfdgtw/npm_install_for_different_platforms_nodegyp_build/) on Reddit, as I am totally blank on how to solve this. I'll fix this ASAP as it's top of my list, but I need to know how. Any input is welcome. In the meantime I'm trying to do research.

**Comment by jerri** [comment]
Mhm. The easist approach would probably be creating a docker environment with a linux distribution and do the npm install there. This way you would get a linux executable. Not sure though, if this is actually going to be compatible with all kinds of linux systems. The linux environment is quite complex.
But maybe it makes more sense for the people to create the runtime themselfes. It shouldn't be that complicated, unless you require a lot of dependencies. I think providing binaries is a bad idea in any case.

**Comment by kkoomen** [comment]
So, I got a good solution; GitHub Actions. It supports all three environments and I can use this to build, test and publish for all platforms. I'll set it up this weekend and will let y'all know when I have a beta version available to test.

**Comment by kkoomen** [comment]
Update: The first setup is done for GitHub Actions and right now it works well for MacOS + Linux, see [run #323273931](https://github.com/kkoomen/vim-doge/actions/runs/323273931)but these are just the tests. This weekend I'll add another workflow to build a release. When I have beta release I'll post another update here.

**Comment by kkoomen** [comment]
[v3.3.2-beta.24](https://github.com/kkoomen/vim-doge/releases/tag/v3.3.2-beta.24) is the first complete version with all tests passing for macos + linux and has binaries being built on the corresponding systems.

@promisedlandt @jerri Can y'all pull the latest master version, run `call doge#install()` and test the linux binary? It should work since the binary is built on ubuntu.

**Comment by promisedlandt** [comment]
I can confirm it works now, but I didn't use the script, just downloaded in manually. 
Thanks for the quick resolution! I think this plugin will be very useful :)
