### ISSUE TITLE
Support neovim?

### ISSUE THREAD

**Issue by deeuu** [kkoomen/vim-doge#12]
```
[DoGe] Unsupported version. Vim v8.0.1630+ is required.
```
Any plans to support neovim?

Thanks for the plugin!

**Comment by kkoomen** [comment]
We support NeoVim. Can you give me more information on which exact version you want to be supported?

**Comment by kkoomen** [comment]
This might be a wrong check though. I'll look into it. We should support nvim 0.3.2+

**Comment by kkoomen** [comment]
@deeuu It should be fixed now in [v1.4.3](https://github.com/kkoomen/vim-doge/tree/v1.4.3).

Please confirm towards me whether this issue has been fixed by now.

**Comment by kkoomen** [comment]
It was indeed a check that was wrong. It's fixed in [v1.4.3](https://github.com/kkoomen/vim-doge/tree/v1.4.3).

If you experience more issues, feel free to submit new issues.

**Comment by deeuu** [comment]
Working - thanks for the quick fix!
