### ISSUE TITLE
Add support for Rust

### ISSUE THREAD

**Issue by Qyriad** [kkoomen/vim-doge#13]
I was actually kind of surprised to see that neither is Rust supported, nor is there an open issue for it. Though admittedly I haven't really looked for Rust documentation Vim plugins, this particular plugin seems quite nice.  
Rust has special documentation comments: `///` and `//!`. (It also supports markdown in its comments)

**Comment by kkoomen** [comment]
I can look into Rust. If you can tell me type of doc standard you want to be supported including a link towards the documentation of all available tags I can implement it eventually.

**Comment by kkoomen** [comment]
@Qyriad can you provide me with a doc standard? If you can't provide anything I will close this issue.

**Comment by vigoux** [comment]
There is not clear format, but guidelines are given [here](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text).

**Comment by hydeik** [comment]
Hi, 

I also would like to use this plugin with Rust.
Rust accepts the Markdown style comment for documentation.
We can find some examples of documentation comments in
- https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html
- https://doc.rust-lang.org/rust-by-example/meta/doc.html
- https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text

The template for a Rust function could be something like:

```rust
///
/// [TODO:description]
///
/// # Arguments
///
/// * `arg1` - [TODO:description]
/// * `arg2` - [TODO:description]
///
pub fn my_func(arg1: i32, arg2: f64) -> f64 {
    // ...
}
```

**Comment by kkoomen** [comment]
@hydeik Thanks for your well done comment and further explanation.

I do have some further questions that don't seem to be clear to me yet:
- Is the empty line at the top needed? Looking at your links they do not prefix the doc block with an empty `///`. Is this needed?
- What's the name of the doc standard? From your links the name seems to be 'cargo' as the doc standard name. If this is right then this will be the default name for rust. This will lead to a configurable option such as: `let g:doge_doc_standard_rust = 'cargo'`.
- Can you provide me a good and clear example of what a comment should look like? Looking at your example function `pub fn my_func(arg1: i32, arg2: f64) -> f64 { ... }` I can spot at least the parameters along with the return type so I assume `# Arguments` would be a category and `# Returns` maybe? I don't know. Please provide a clear example for me of what a _real_ and _good_ generated comment may look like.
- The parameters do only have the parameter name in it ```/// * `arg1` - [TODO:description]```, but looking at https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html they mention it should have the parameter type as well. Once again: please provide me with a good example of what a real and good comment may look like.
- What's the difference between `///` and `//!`? Which one should be used? Looking at the docs I assume `///` to support markdown.
- Should a comment have a summary followed by a more detailed description or only a description?
- Would you be able to help out during development? If you have proper Rust knowledge (assuming you do) then I'd love some feedback of you about different scenario's I'll write a use-case for.

**Comment by hydeik** [comment]
>     * Is the empty line at the top needed? Looking at your links, they do not prefix the doc block with an empty `///`. Is this needed or your fault?

No, not necessary.

>     * What's the name of the doc standard? From your links the name seems to be `cargo` as the doc standard name. If this is right then this will be the default name for rust. This will lead to a configurable option such as: `let g:doge_doc_standard_rust = 'cargo'`.

The name documentation style is Markdown. The lines including `/// # Keyword` are treated as a header. We can use arbitrary keywords here, (Arguments, Returns, Examples, Safety, Error, etc.)

If you need some convention used in vim-doge, `let g:doge_doc_standard_rust = 'rustdoc'` might be a proper choice (rustdoc is the name of a standard tool for processing documentation comments).

 >     * Can you provide me a good and clear example of what a comment should look like? Looking at your example function `pub fn my_func(arg1: i32, arg2: f64) -> f64 { ... }` I can spot at least the parameters along with the return type so I assume `# Arguments` would be a category and `# Returns` maybe? I don't know. Please provide a clear example for me of what a _real_ and _good_ generated comment may look like.
> 
>     * The parameters do only have the parameter name in it `` /// * `arg1` - [TODO:description] ``, but looking at https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html they mention it should have the parameter type as well. Once again: please provide me with a good example of what a real and good comment may look like.
> 

Source codes of standard library could be good examples.
The source code of `std::vec::Vec` can be found at https://doc.rust-lang.org/src/alloc/vec.rs.html.
The html file generated from this source file looks like https://doc.rust-lang.org/std/vec/struct.Vec.html.

Actually, standard library do not provides list of arguments or return values. Instead, they provides 
Examples section with code blocks in Markdown style.


>     * What's the difference between `///` and `//!`? Which one should be used? Looking at the docs I assume `///` to support markdown.
> 

`//!` is generally used for the description of modules/crates, while `///` is used for documenting other stuff (function, struct, variable, etc.)

>     * Should a comment have a summary followed by a more detailed description or only a description?
> 

I think the latter option is enough.

>     * Would you be able to help out during development? If you have proper Rust knowledge (assuming you do) then I'd love some feedback of you about different scenario's I'll write a use-case for.

I will do help as much I can. Unfortunate things is I just started to use Rust very recently.
I also expects comments from Rust experts.

**Comment by kkoomen** [comment]
@hydeik I'm sorry that I didn't do this issue, as I simply forgot about it. Recently I did a rewrite to use tree-sitter parsers instead of plain ol' regex. See #101 

Tree-sitter also supports Rust and I will support this soon, as it is top of my list.

**Comment by kkoomen** [comment]
To give another update, the `tree-sitter-rust` had an issue in the current version, therefore I was unable to install the package. Recently it did had updates, so I'll try to make some time soon to implement this. I've been busy lately, sorry I couldn't make time. I'll try to implement it ASAP.

**Comment by kkoomen** [comment]
@LanderMoerkerke @arxra @promisedlandt @etrnal70 @lynndylanhurley @kongjun18 @FRostri @wfxr Since you've all add a reaction to [this](https://github.com/kkoomen/vim-doge/issues/13#issuecomment-705317674) comment, I'd like y'all to have a look at [Add support for Rust #290](https://github.com/kkoomen/vim-doge/pull/290) and let me know what situations I have to cover. Basic support for functions is available in the PR with supports for the `Arguments`, `Examples`, `Errors` and `Safety` sections. Please read the description if you want to test the branch locally.

I will merge the PR this Sunday unless you all have suggestions that are mentioned inside the PR.
