### ISSUE TITLE
[Request] Auto-Folding

### ISSUE THREAD

**Issue by GGCristo** [kkoomen/vim-doge#140]
Greetings, I was wondering if it could be possible to create folding in the documentation, activating it with some variable like g:doge_folding (Default: 0).

Maybe changing the 'foldexpr' (http://vimdoc.sourceforge.net/htmldoc/options.html#'foldexpr') variable should be enough, but I am not sure how hard this could be to achieve this with all the supported languages, and working perfectly.

**Comment by kkoomen** [comment]
What exactly do you expect? Do you want to add folding markers inside the docblock?

**Comment by GGCristo** [comment]
Actually I don't mind the “how” is done, one of the problem I find navigation the code is that documentation obviously make the file larger, it could be activating the folding with a keypress or automatically when you finish writing the last TODO.

Also, I have doubts if this is something that should be managed by the user or if it could be a nice extra feature of this plugin, so I understand if you think this is an overkill feature.

**Comment by kkoomen** [comment]
If enough people would care about this then I'm always open to ideas but to be honest, this is out of scope for this plugin and it is up to the user to add folding.

If folding is too much work for you then you might want to add a custom keybinding where you can quickly select comment blocks and add folding markers to your selection.
