### ISSUE TITLE
Error when installing with Plug

### ISSUE THREAD

**Issue by sQVe** [kkoomen/vim-doge#154]
**Describe the bug**

I'm trying to install the plugin with `Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }` but it fails with:

```
x Post-update hook for vim-doge ... Vim(call):E121: Undefined variable: g:doge_dir
```

**Comment by subnut** [comment]
Can't reproduce.
Please include a minimal `.vimrc` required to reproduce this issue.

**Comment by sQVe** [comment]
Strange. Tried to replicate this now and wasn't able to. Closing until I see it again. :+1:
