### ISSUE TITLE
Please implement some way to check the version of the compiled executable

### ISSUE THREAD

**Issue by subnut** [kkoomen/vim-doge#155]
**Is your feature request related to a problem? Please describe.**
`doge#install()` deletes an existing installation even if it is at the current version, and re-installs. This causes unnessecary data-consumption, and also, till the new binary is installed, the user cannot continue working.

**Describe the solution you'd like**
Implement a command-line-option `--version`, so that `doge#install()` can check the values of `vim-doge --install` and the `.version` file. If they match, then stop without deleting and report to the user that _vim-doge is already installed_. If they don't, then continue as we currently do (delete and re-install)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kkoomen** [comment]
Version check is acceptable yes. This is fairly easy since we already know the version when installing. I'll implement it this weekend.

**Comment by subnut** [comment]
I'd like to see this feature included in `3.6.0` if possible..

**Comment by kkoomen** [comment]
I'll do it this weekend, no worries.
