### ISSUE TITLE
Unknow function: doge#helpers#deepextend

### ISSUE THREAD

**Issue by fgheng** [kkoomen/vim-doge#156]
**Describe the bug**
Hello, I use vim-plug as plugin manager, I write `Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }` in my vimrc file, and when I use `PlugInstall` to install vim-doge, error occurced:
```
Unknow function: doge#helpers#deepextend
```
![image](https://user-images.githubusercontent.com/50551377/99178379-7ee78800-274d-11eb-9749-38377dc58eb2.png)

**Comment by kkoomen** [comment]
Please provide a minimal vimrc on how to reproduce this. If you can't then I'm closing this soon, because I can't run into this issue.

**Comment by fgheng** [comment]
hello, my minimal vimrc is below:

```viml
call plug#begin( '~/.cache/vim/plugin/')
Plug 'kkoomen/vim-doge', {'do': {-> doge#install()}, 'on': 'DogeGenerate'}
call plug#end()
```
the problem is still exist.

**Comment by fgheng** [comment]
Problems occured when I used command `:PlugInstall`

**Comment by kkoomen** [comment]
Next time, please read the docs before making issues. The README clearly states that you should use 

```vimrc
Plug 'kkoomen/vim-doge', {'do': {-> doge#install()}}
```

instead of 

```vimrc
Plug 'kkoomen/vim-doge', {'do': {-> doge#install()}, 'on': 'DogeGenerate'}
```

Removing the `'on': 'DogeGenerate'` part will fix your problem.

**Comment by shyun3** [comment]
I am also running into this on Neovim v0.6:
![image](https://user-images.githubusercontent.com/37260523/145694039-0940e457-a09a-4408-b317-e7d3356e98cf.png)

Here is my minimal `init.vim`:
```vim
let g:vimDir = stdpath('config')

call plug#begin(g:vimDir . '/bundle')
Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }
call plug#end()
```

**Comment by kkoomen** [comment]
@shyun3 see #358 for the latest updates on this.
