### ISSUE TITLE
Always destructures props

### ISSUE THREAD

**Issue by yan42685** [kkoomen/vim-doge#169]
**Describe the bug**
Configuration for disabling destructuring params doesn't take effect.
```vim
let g:doge_javascript_settings = {
\  'destructuring_props': 0,
\}
```

**To Reproduce**

- Create file `doge.vim` with:

```vim
call plug#begin('~/.vim/plugged')
Plug 'kkoomen/vim-doge', {'do': { -> doge#install() }, 'on':['DogeGenerate']}
let g:doge_javascript_settings = {
\  'destructuring_props': 0,
\}
call plug#end()
```

- Start neovim with command: `nvim -u doge.vim test.js`

1.  write a function
2. `:DogeGenerate`

**Expected behavior**
Generate doc without @param.

**Screenshots**
![doge](https://user-images.githubusercontent.com/41834091/99941243-a8855c80-2da8-11eb-93e9-ccfba9f2cabf.png)

**Output of `nvim --version`**

NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/snapcraft-nvim-136142/parts/nvim/build/build/config -I/build/snapcraft-nvim-136142/parts/nvim/build/src -I/build/snapcraft-nvim-136142/parts/nvim/build/.deps/usr/include -I/usr/include -I/build/snapcraft-nvim-136142/parts/nvim/build/build/src/nvim/auto -I/build/snapcraft-nvim-136142/parts/nvim/build/build/include
Compiled by root@lcy01-amd64-026

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by kkoomen** [comment]
You're not understanding what *destructuring* means.

This is destructuring (1 variable, but using `{...}` you can extract the keys inside the object as variables that are directly accessible:

```js
function test({ children, ...props }) {}
```

and this is not (just regular function parameters): 

function test(children, ...props) {}

**Comment by yan42685** [comment]
Thank you very much for your prompt and detailed reply, I have figured out the difference. 😄

**Comment by kkoomen** [comment]
I just noticed I did made some mistakes in my previous comment. Have a look again, because I fixed my typos.

**Comment by yan42685** [comment]
Ok, I get it now, thanks~
