### ISSUE TITLE
Add TSDoc doc standard for TypeScript

### ISSUE THREAD

**Issue by Couto** [kkoomen/vim-doge#198]
**Documentation standard**

Link: https://tsdoc.org/

**How popular is the doc standard?**
- [ ] Not popular at all
- [ ] Some people use it
- [ ] Quite a lot of people use it
- [x] It's not the most popular one, but a good alternative
- [ ] Everyone is using it

**Comment by Couto** [comment]
I followed the Issue template, however I'm not entirely sure if that's all the info you need, let me know if you have questions, I'm happy to answer the best I can.

**Comment by kkoomen** [comment]
@Couto What would be the difference with the current implementation with [`jsdoc`](https://jsdoc.app/)? The information that vim-doge is providing is the same syntax as the TSDoc as far as I see.

**Comment by VVKot** [comment]
@kkoomen I guess there are some minor additions like [@decorator](https://tsdoc.org/pages/tags/decorator/); but I mostly I *don't* want types specified for params as it is redundant for Typescript. Wonder if this can at least be another option for `jsdoc` standard?

**Comment by kkoomen** [comment]
@VVKot I honestly have been busy lately and totally forgot about this and also did forgot that there's an open PR for this already. I'll look into it ASAP.

**Comment by kkoomen** [comment]
This feature has been merged and released in [v3.10.0](https://github.com/kkoomen/vim-doge/tree/v3.10.0).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
