### ISSUE TITLE
Make documentation patterns configurable

### ISSUE THREAD

**Issue by gbcreation** [kkoomen/vim-doge#20]
**Is your feature request related to a problem? Please describe.**
When I write docblocks manually in JavaScript source files, I write the description of functions without the @description prefix. I would like to have a way to configure DoGe to make the @description keyword optional.

**Describe the solution you'd like**
Provide global DoGe configuration variables to enable / disable some prefixes in docblocks.

**Describe alternatives you've considered**
A probably better solution would be to be able to configure the documentation patterns in `.vimrc` / `init.vim` in a similar way to what is done for `b:doge_patterns`. It would be also a great mean to support additional languages, and to share patterns among the community of DoGe users.

**Comment by kkoomen** [comment]
> When I write docblocks manually in JavaScript source files, I write the description of functions without the @description prefix. I would like to have a way to configure DoGe to make the @description keyword optional.

I prefer this one as well, yet I assumed jsdoc would require the `@description` tag (more info [here](https://jsdoc.app/tags-description.html)). Asking around in IRC chat let me to the conclusion that your request should be used. I'll adjust this right away. Both are correct according to JSDoc and I know that using the start of the comment block to write your description is the most used way by the javascript community.

**Comment by kkoomen** [comment]
I will remove the `@description` since that it the problem for you. If there's a big _need_ to configure the pattern globally through your vimrc I'll add it, but only if there's a big need for it by many people.

**Comment by kkoomen** [comment]
The `@description` has been removed in [v1.4.7](https://github.com/kkoomen/vim-doge/tree/v1.4.7).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.

**Comment by gbcreation** [comment]
Thank you for removing the `@description` keyword.
