### ISSUE TITLE
Add Sphinx doc standard for python

### ISSUE THREAD

**Issue by vigoux** [kkoomen/vim-doge#21]
**Documentation standard**
Current `reST` doc standard does not conform to `Sphinx` one, is it possible to add it ?
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format

**How popular is the doc standard?**
- [ ] Not popular at all
- [ ] Some people use it
- [ ] Quite a lot of people use it
- [X] It's not the most popular one, but a good alternative
- [ ] Everyone is using it

**Comment by kkoomen** [comment]
I'll close this issue and will continue the discussion on #23.
