### ISSUE TITLE
Author comment

### ISSUE THREAD

**Issue by nagy135** [kkoomen/vim-doge#231]
**Is your feature request related to a problem? Please describe.**
I dont see any current option to add this to a docstring

**Describe the solution you'd like**
I would like :DogeGenerate to also include @author line with:
`Firstname Lastname <email>` 

**Describe alternatives you've considered**
Maybe this is somehow possible with templates? I think this should be one line in my vimrc to allow this feature.

Tried to follow your issue template...If I m just not seeing this feature, please let me know how to enable it.

**Comment by kkoomen** [comment]
It's not built into the plugin. You can use [`DogeCreateDocStandard`](https://github.com/kkoomen/vim-doge#dogecreatedocstandard-doc_standard) like so: `:DogeCreateDocStandard phpdoc` and extend the exiting doc standard to include `@author`.

**Comment by nagy135** [comment]
Thats nice (thanks for tutorial) and as i said i kinda expected this, but It still took me while to figure out what it neede me to do to make it work ...would be nice to have simple vimrc option for this to apply to every standard
