### ISSUE TITLE
Adding custom doc standard

### ISSUE THREAD

**Issue by kristijanhusak** [kkoomen/vim-doge#232]
Hi,

is there a way to add a custom doc standard, but without the `/after/ftplugin` file?

I tried this, but it doesn't work:
```
autocmd FileType javascript call s:setup_jsdoc()

function! s:setup_jsdoc()
  call doge#buffer#register_doc_standard('jsdoc_custom', [...])
  let b:doge_doc_standard = 'jsdoc_custom'
endfunction
```

I get an error that it doesn't exist.

**Comment by kkoomen** [comment]
I suggest you read about [`DogeCreateDocStandard`](https://github.com/kkoomen/vim-doge#dogecreatedocstandard-doc_standard) command first. That's the way to go for custom adjustments to any doc standards or if you want to create a new one yourself.

**Comment by kristijanhusak** [comment]
I read about it. When I run the command, it creates an `after/ftplugin/standard.vim` file, with the new doc standard data. 
I'm asking is there a way to add a new standard without having to create that file?

**Comment by kkoomen** [comment]
It does _not create_ the file. It opens a new buffer with a predefined path for saving. If you want to extend doc standards with your own custom implementation then using the `DogeCreateDocStandard` is the way to go.
