### ISSUE TITLE
Update existing docstring in python

### ISSUE THREAD

**Issue by vigoux** [kkoomen/vim-doge#28]
**Is your feature request related to a problem? Please describe.**
As mentionned in #18, it seems possible to implement the update of existing documentation for some languages (those who have clear delimiters for the documentation, like python)

**Describe the solution you'd like**
Kind of an update of the current documentation of the function, imo it seems possible for at least python and doxygen (that have clear delimieters).

**Describe alternatives you've considered**
Haven't found any other solution yet, despite updating everything by hand.

**Additional context**
Something like this :
```python
def my_func(arg1, arg2):
    """
    A useful docstring
    """
    print("That's useful")
```
Turns into that :
```python
def my_func(arg1, arg2):
    """
    A useful docstring

    :param arg1: [TODO:description]
    :type arg1: [TODO:type]
    :param arg2: [TODO:description]
    :type arg2: [TODO:type]
    """
    print("That's useful")
```

**Comment by kkoomen** [comment]
I'll look into it by the end of the week.

**Comment by JanikvA** [comment]
+1. Was about to create an issue for exactly this! would be super convenient and not to hard to implement imo.

btw loving this plugin so far =)

**Comment by kkoomen** [comment]
Closing this because of duplicate. Further discussion can be held at #18.
