### ISSUE TITLE
Does not work, even with minimal vimrc

### ISSUE THREAD

**Issue by VVKot** [kkoomen/vim-doge#285]
**Describe the bug**

I am facing the same issue as in #283 - pressing `<Leader>d` does not add comment but modifies the file. I tried the trouble-shooting steps from https://github.com/kkoomen/vim-doge/issues/107#issuecomment-707079124, `tree-sitter` is installed for me, the line you suggested to log returns empty string (hence it consistent with what I see - file is modified but there are no visual changes). I installed plugin with https://github.com/wbthomason/packer.nvim if that makes any difference.

It also behaves the same way with minimal vimrc. Any other tips to figure out what's wrong?

**Settings**

None.

**To Reproduce**

- Create file `doge.vim` with:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```

- Start (neo)vim with command: `vim -u doge.vim`

1. Press `<Leader>d` with cursor over Typescript function.
2. No comment added, buffer is modified.

**Expected behavior**

1. Comment is added.

**Screenshots**

--

**Output of `vim --version`**

NVIM v0.5.0-dev+1126-g0496b572a

**Comment by kkoomen** [comment]
I'm using nvim v0.4.4 compiled with brew  and vim 8.2.2500 and have no issues at all using the latest version. You're using NVIM v.0.5.0-dev which could be the problem. That's a risk you take yourself, because I'm not gonna support `dev` versions.

Make sure you got the latest binary installed.
You can try to do the following:

1) Open up `test.js` with the following contents:

```ts
function test() {}
```

2) Run the following command: `node ~/path/to/vim-doge/bin/vim-doge test.js typescript 1 function`, this should result in:

`{"visibility":null,"static":false,"generator":false,"async":false,"name":null,"typeParameters":[],"parameters":[{"name":"test","type":null,"default":null,"optional":false}],"returnType":null,"exceptions":[]}`

What do you get?

**Comment by VVKot** [comment]
@kkoomen thanks! To make sure that it is not Neovim's dev version interfering, I also tried this with Vim 8.2.2500 and vim-plug, just to make sure. In both cases I get the error below:

```
����


SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1022:15)
    at Module._compile (node:internal/modules/cjs/loader:1056:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

shell returned 1
```

**Comment by VVKot** [comment]
`:set fileencoding` in `bin/vim-doge` returns `utf-8`. I tried node versions `v15.11.0`, `v12.20.2`, `v10.23.0` - same for all of them. I am on Macos if that makes a difference?

**Comment by kkoomen** [comment]
I am on MacOS as well and everything works for me. 

Try to run `npm run build` inside the vim-doge folder and then run `node ~/path/to/vim-doge/bin/vim-doge test.js typescript 1 function` again, what do you get?

**Comment by VVKot** [comment]
@kkoomen yes, that fixes it! Do you know why it might behave that way? Something with version/settings of node that is used to build the binary?

**Comment by VVKot** [comment]
Ah I see, it now uses my local packages instead of building a binary with `pkg`. Maybe the fork submodule-d into the repo needs a bump? Don't know.

**Comment by kkoomen** [comment]
Can you now do `rm ./bin/vim-doge`, open vim / neovim and do `:call doge#install()`. It should get the latest version of vim-doge. After the download is complete, see if doge is working now.

**Comment by VVKot** [comment]
I tried that before and just tried again - installing binary brings the error back.

**Comment by kkoomen** [comment]
@VVKot May I know the exact system version of MacOS you're using? vim-doge still works for me on Big Sur and on another laptop with Catalina and both work.

**Comment by VVKot** [comment]
Catalina 10.15.7. Can try on Big Sur in a bit, I believe I was hitting the same problems.

**Comment by VVKot** [comment]
Same deal on Big Sur 11.1, node 15.11.0 - I removed the script, downloaded the latest again (3.7.0), getting "Invalid or unexpected token" on the first line.

**Comment by kkoomen** [comment]
mhm, doing a build locally also lets me run into this error, but if I use the build from [here](https://github.com/kkoomen/vim-doge/releases/tag/v3.7.0) then I don't have any problems.

**Comment by VVKot** [comment]
@falcucci do you mind doing `rm ./bin/vim-doge` and `npm install && npm run build` in your vim-doge install location? Want to understand if this https://github.com/kkoomen/vim-doge/issues/285#issuecomment-792265764 helps you too.

**Comment by kkoomen** [comment]
@VVKot Issue should be fixed. Can you upgrade vim-doge to use v3.8.0? This version works for me.

**Comment by VVKot** [comment]
Yay, this indeed fixed the problem! 🎉 Tested both Catalina and Big Sur with 3.8.1.
Thanks so much for a prompt resolution. ❤️

**Comment by falcucci** [comment]
well done guys, the new release worked like a charm. thank you all
