### ISSUE TITLE
macOS v3.8.1 binary shows "MODULE_NOT_FOUND"

### ISSUE THREAD

**Issue by klauer** [kkoomen/vim-doge#291]
**Steps to reproduce the behavior:**

1. Download vim-doge on macOS version v3.8.1 (even outside of vim/nvim)
2. Run vim-doge in terminal (or trigger it in vim by way of `:DogeGenerate` with same result)

```node
$ ./vim-doge
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/var/folders/9t/8vhvhgv55mjgfd84rczmr811793f3f/T/caxa/vim-doge/kjs5vrtlpk/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Expected behavior**

v3.8.0 does not appear to have this issue. Downgrading seems to help.

**Comment by kkoomen** [comment]
What version of macOS are you running? I'm running the latest version of Big Sur and have no issues. I've had other people on other issues that also use macOS issues but 3.8.1 fixed everything.

**Comment by klauer** [comment]
I'm on 11.2.2 (20D80).  I understand that the binary shouldn't be doing anything with no arguments. The reason I noted the output with empty arguments is that it differed from the versions: the working one output `Could not load parser for undefined` (understandably so), whereas the failing one output the traceback in the original issue.

Interestingly, I tried `:DogeGenerate` again this morning including the reversion to `v3.8.0` and got the same `MODULE_NOT_FOUND` error. _So_, I'd guess this is something weird in my environment and not necessarily a problem with v3.8.1.

And then upgrading again to v3.9.0 is working now. 

If there's anything else I can provide as far as environment details, should this pop up again, please let me know and I'll report back.

And also apologies for any wasted time here, and thanks for the very cool vim plugin! 👍

**Comment by tuna-f1sh** [comment]
I know this is closed but I also get this on my macOS system (11.2.3) with 3.9.0.

```
﻿❯ ./bin/vim-doge test.js typescript 1 function_declaration | pbcopy
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/var/folders/2f/qc594kl50bb08ghcmyzrnd780000gn/T/caxa/vim-doge/wrarz5ys39/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I did a bit of digging in an attempt to understand why. If I `npm install` and `npm build:binary:unix` I get:

```
❯ ./bin/vim-doge test.js typescript 1 function_declaration
{"visibility":null,"static":false,"generator":false,"async":false,"name":"test","typeParameters":[],"parameters":[{"name":"foo","type":null,"default":null,"optional":false}],"returnType":null,"exceptions":[]}
```

And now the vim-doge works in `vim`. Could the downloaded unix binary now not be compatible with macOS?

**Comment by kkoomen** [comment]
@leafac do you know _why_ this happens? I personally don't have this issue locally on both 10.15 and on 11.x.

**Comment by leafac** [comment]
I don’t know… I’ll look into it…

**Comment by leafac** [comment]
Looked some more into this. I still don’t have a good answer. As far as caxa is concerned, it seems like everything was extracted, because the error is happening in JavaScript land, which means Node.js was activated. From that point on, something was going wrong in the application itself, but I don’t know what…

In any case, it seems like it’s no longer an issue, right?
