### ISSUE TITLE
Generated Numpy API documentation out of sync with pylint's interpretation

### ISSUE THREAD

**Issue by scottbolte** [kkoomen/vim-doge#296]
**Describe the bug**

The generated Python docstring for a function, using Numpy style, provokes warnings from pylint. Specifically, from pylint's pylint.extensions.docparams plugin. It is a great plugin since it will notify me when the API docstring is no longer in sync with an evolving function signature.

See below for before & after examples, but in a nutshell, these two changes are needed:
1. add line continuation after the opening triple quote
2. remove the trailing colon on the type in the Returns section 

**Settings**

DoGE settings:

```vim
let g:doge_doc_standard_python = 'numpy'
```

Relevant pylint settings via `pylintrc` file:

```
load-plugins=pylint.extensions.docparams,pylint.extensions.docstyle,pylint.extensions.typing
```

**To Reproduce**

Two python functions below. Line numbers included to correlate with `pylint` error messages.

The first functions's API docstring (lines 29-42) is what DoGe generates. It provokes the pylint errors seen on lines 35 & 36.

The second function has two slight modifications on lines 47 & 56 -- see comments at lines 50-52 for details -- that keep pylint happy.

```

    28	def first_example() -> str:
    29	    """
    30	    Simplified function to demonstrate return code problem.
    31
    32	    This DoGe generated docstring will provoke the following warnings from
    33	    pylint with the pylint.extensions.docparams plugin loaded:
    34
    35	        demo.py:28:0: C0199: First line empty in function docstring (docstring-first-line-empty)
    36	        demo.py:28:0: W9011: Missing return documentation (missing-return-doc)
    37
    38	    Returns
    39	    -------
    40	    str:
    41	        standard greeting.
    42	    """
    43	    return "hello world"
    44
    45
    46	def second_example() -> str:
    47	    """\
    48	    Simplified function to demonstrate how to remove pylint errors.
    49
    50	    Adding the '\' character after the triple quotes above suppresses C0199.
    51
    52	    Removing the : after "str" below suppresses the W9011 warning.
    53
    54	    Returns
    55	    -------
    56	    str
    57	        standard greeting.
    58	    """
    59	    return "hello world"
```

**Expected behavior**

The Numpy specification, at least according to https://numpydoc.readthedocs.io/en/latest/format.html#returns, does not include a trailing ':' after the return type.

Taking pylint's warnings at face value, the first line of a docstring may not be empty and a bare """ on a line counts as empty.

**Comment by kkoomen** [comment]
@scottbolte Hi, thanks for your suggestion!

I've created a PR with passing tests etc that I want you to have a look at. If you approve, place a comment at that PR where you mention that you approve the changes. If you have suggestion, feel free to leave comments on the PR.

If you approve, I will merge it as soon as possible.

**Comment by scottbolte** [comment]
I'll look at the PR, but it likely will need to change. I just found out that while `pylint` accepts a trailing line continuation after the opening triple quote, `flake8` does not. The compromise to make them both happy is to start the text on the same line as the opening quotes.

**Comment by kkoomen** [comment]
@scottbolte let's continue this discussion at the PR.

**Comment by kkoomen** [comment]
Closed due to inactivity.
