### ISSUE TITLE
typescript doc generation error.

### ISSUE THREAD

**Issue by yuhuihu** [kkoomen/vim-doge#298]
**Describe the bug**

typescript file with   < **leader** > d 

Errors:
```
[DoGe] typescript parser failed
[Doge] Exception: Vim(return):E474: Trailing characters: /06/15 11:52:50 caxa stub: Failed to run command: fork/exec /var/folders/4j/y02zqzld1w9_hy0l5rvhgx5r0000gn/T/caxa/vim-doge/mmrbsz8xsq/node_mod
ules/.bin/node: no such file or directory
2021/06/15 11:52:50 caxa stub: Failed to run command: fork/exec /var/folders/4j/y02zqzld1w9_hy0l5rvhgx5r0000gn/T/caxa/vim-doge/mmrbsz8xsq/node_modules/.bin/node: no such file or directory
[DoGe] typescript parser failed
[Doge] Exception: Vim(return):E474: Trailing characters: /06/15 11:52:50 caxa stub: Failed to run command: fork/exec /var/folders/4j/y02zqzld1w9_hy0l5rvhgx5r0000gn/T/caxa/vim-doge/mmrbsz8xsq/node_mod
ules/.bin/node: no such file or directory
2021/06/15 11:52:50 caxa stub: Failed to run command: fork/exec /var/folders/4j/y02zqzld1w9_hy0l5rvhgx5r0000gn/T/caxa/vim-doge/mmrbsz8xsq/node_modules/.bin/node: no such file or directory
[DoGe] typescript parser failed
[Doge] Exception: Vim(return):E474: Trailing characters: /06/15 11:52:50 caxa stub: Failed to run command: fork/exec /var/folders/4j/y02zqzld1w9_hy0l5rvhgx5r0000gn/T/caxa/vim-doge/mmrbsz8xsq/node_mod
ules/.bin/node: no such file or directory
2021/06/15 11:52:50 caxa stub: Failed to run command: fork/exec /var/folders/4j/y02zqzld1w9_hy0l5rvhgx5r0000gn/T/caxa/vim-doge/mmrbsz8xsq/node_modules/.bin/node: no such file or directory
```

**Settings**
no any custom setting added.
""""""""""""""""""""
" doge 
"
let g:doge_enable_mappings = 1
let g:doge_mapping_comment_jump_forward = 1
let g:doge_mapping_comment_jump_backward = 1

**To Reproduce**

- Create file `doge.vim` with:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```

- Start (neo)vim with command: `vim -u doge.vim`

1. ...

**Expected behavior**

normal documentation.

**Screenshots**

<img width="1750" alt="截屏2021-06-15 上午11 55 41" src="https://user-images.githubusercontent.com/4496921/121990624-a5979b00-cdd0-11eb-8391-de4b76402cfd.png">

**Output of `vim --version`**

:version
NVIM v0.5.0-dev+1398-gd09b8ad71
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-para
meter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLAR
ATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work
/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/
Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
编译者 runner@Mac-1623473949397.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/share/nvim"

Run :checkhealth for more info

#### os
macOS Big Sur 11.4

**Comment by erancx** [comment]
I'm seeing the exact same issue with `NVIM v0.5.0-dev+nightly-335-g96d83e2a6` and Python doc generator.

**Comment by kkoomen** [comment]
I've had this issue as well. A simple fix would be to build locally:

```
$ npm i
$ npm run build
```

I personally experience some issues as well, but that's because I'm running on the new M1 macbook lately. I need to find some proper solutions for all these compatibilities.

**Comment by marioidival** [comment]
@kkoomen I missing something?
npm i
npm run build

```emove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/tree_sitter_runtime_binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/kakarotto/.asdf/installs/nodejs/16.4.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/Users/kakarotto/.asdf/installs/nodejs/16.4.2/bin/node" "/Users/kakarotto/.asdf/installs/nodejs/16.4.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/kakarotto/codes/temp/vim-doge/node_modules/tree-sitter
npm ERR! gyp ERR! node -v v16.4.2
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kakarotto/.npm/_logs/2021-07-15T09_12_20_834Z-debug.log```

**Comment by kkoomen** [comment]
@marioidival let me guess, you're using M1 Macbook?

**Comment by marioidival** [comment]
@kkoomen yes Y_Y

**Comment by kkoomen** [comment]
@marioidival I also experiences issues with M1 and treesitter and Node v16. You should open your terminal using Rosetta, then reinstall node to v15 and then you should be able to install treesitter through `npm install`.

**Comment by marioidival** [comment]
@kkoomen ok man, thank you!

**Comment by junchao98** [comment]
Brothers I also encountered this problem
```
> $ cat /etc/os-release                                                                                                                                                                                  [±master]
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

```

Manually compiled and solved, Thinks!
