### ISSUE TITLE
Dogegenerate rustdoc gives out an error

### ISSUE THREAD

**Issue by sansyrox** [kkoomen/vim-doge#299]
**Describe the bug**

When I use the command to create rust docs, I get the following error:

```
[DoGe] rust parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/var/folders/4k/tfv95dys49s5syt_t24swgvh0000gn/T/caxa/vim-doge/mmrbsz8xsq/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/var/folders/4k/tfv95dys49s5syt_t24swgvh0000gn/T/caxa/vim-doge/mmrbsz8xsq/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Settings**

Default settings and no bindings as of now.

**To Reproduce**
I followed all the steps for the installation and reporduction. I am using neovim 0.5.0.

And this is the output when I follow the vim steps in the documentation.
E282: Cannot read from "doge.vim"

**Output of `vim --version`**

**Comment by sansyrox** [comment]
Fixed it. This was an error with npm. I used nvm to make the global alias to 14 and it works.

Maybe some incompatibility with v16.

**Comment by kkoomen** [comment]
@sansyrox I've also has issues with v16 lately on my macbook m1 with node, so it's not you for sure.

**Comment by sansyrox** [comment]
@kkoomen , I am using an intel macbook. So I guess there could be some issue with a dependency not supporting node 16 and not with the cpu architecture. 
These are just my 2 cents and I may be entirely wrong too. 😅 

Thanks though for this amazing plugin 🚀
