### ISSUE TITLE
Add support for Numpy style documentation for python

### ISSUE THREAD

**Issue by paulkass** [kkoomen/vim-doge#3]
**Is your feature request related to a problem? Please describe.**
My project uses Numpy documentation style, and I would like to continue using that.

**Describe the solution you'd like**
An option to add documentation styles, in particular the Numpy documentation style.

**Additional context**
Here is the description of the Numpy doc [style](http://daouzli.com/blog/docstring.html#numpydoc).

**Comment by kkoomen** [comment]
The general idea here is to add support for multiple doc styles and I definitely agree! This was something I had on my own todo list as well to implement, but it was optionally for me personally. I'll work on a multi-doc implementation per language ;)

Thanks for your input.

**Comment by kkoomen** [comment]
Multiple doc standard are supported, tested and succesfully merged into the master branch :tada:
