### ISSUE TITLE
typo at prominent place...

### ISSUE THREAD

**Issue by AXGKl** [kkoomen/vim-doge#300]
Hi,

since you never have a second chance to make a first impression I thought I bug you with this one.

Your Splash Image has a big fat Typo :

![](https://user-images.githubusercontent.com/10693490/97796723-7f403900-1c0d-11eb-9633-9a94f48978b9.jpg)

If the 'Genertor' is an intended joke or so I beg a pardon...

**Comment by kkoomen** [comment]
OMG you're a hero. I did re-create the banner which led to a sharper version, but _never_ have noticed this. Thanks!
