### ISSUE TITLE
Will break the highlight under current cursor in typescript

### ISSUE THREAD

**Issue by sainnhe** [kkoomen/vim-doge#301]
**Describe the bug**

![](https://user-images.githubusercontent.com/37491630/124851357-f74cd300-dfd4-11eb-921b-86e23396d4f6.png)

![](https://user-images.githubusercontent.com/37491630/124851361-fa47c380-dfd4-11eb-9122-3c1f2a1300d1.png)

As you can see, when I move the cursor to a variable, the highlight breaks (`myvar` should be red).

This happens only in typescript, there is no such problem in javascript.

The expected behavior:

![](https://user-images.githubusercontent.com/37491630/125148158-e92cbd00-e162-11eb-934c-ee30ac577a27.png)

I used to think that this bug was caused by either coc-highlight or nvim-treesitter, but these two plugin works nicely together, the bug only appears when this plugin is enabled. See related issue here https://github.com/nvim-treesitter/nvim-treesitter/issues/1528

**Settings**

**To Reproduce**

- Create file `doge.vim` with:

```vim
call plug#begin(fnamemodify(stdpath('data'), ':p') . 'plugins')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'kkoomen/vim-doge', {'do': 'npm ci && npm run build:binary:unix -- vim-doge'}
call plug#end()

let g:coc_data_home = fnamemodify(stdpath('data'), ':p') . 'coc'
let g:coc_global_extensions = ['coc-highlight', 'coc-tsserver']

set updatetime=100
augroup CocCustom
  autocmd!
  autocmd CursorHold * call CocActionAsync('highlight')
augroup END

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  }
}
EOF

set termguicolors
colorscheme desert
hi! link typescriptVariableDeclaration Normal " White
hi! link TSVariable Function " Green
```

- Start (neo)vim with command: `nvim -u doge.vim`

1. Create a ts file with the following content:

```typescript
let myvar = { "foo": 1 };
console.log(myvar);
```

2. Place the cursor under `myvar`
3. The foreground color changed from green to white

**Expected behavior**

Only background color should be changed, the foreground color should keep what it is before.

**Screenshots**

**Output of `nvim --version`**

```
NVIM v0.6.0-dev+32-ge43dbfdd0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-git/src/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by kkoomen** [comment]
You're using a neovim development version. Obviously we're not gonna support that until it reached a stable version. If you can reproduce this bug with a stable version of neovim you can write a follow-up comment in here and I will re-open the issue.

**Comment by sainnhe** [comment]
> Obviously we're not gonna support that until it reached a stable version.

I'm very sure this bug can be reproduced in neovim 0.5.0 stable release.

---

> Also, this seems more like a neovim issue.

Of course this is a neovim-only issue, vim does not have any support on tree-sitter.

**Comment by kkoomen** [comment]
I reproduced this with v0.5. I'll debug this in a moment.

**Comment by kkoomen** [comment]
Okay, I found the problem, but it's not related to vim-doge.

If you do `:set ft=javascript` you do get the green version:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/10693490/125162328-7e41ad00-e187-11eb-90f6-bd7063a4a719.png">

If you do `:set ft=typescript` then you do get the white version:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/10693490/125162332-8863ab80-e187-11eb-8a52-57bb58da7477.png">

This is just a syntax issue and doesn't have anything to do with vim-doge, which also makes sense, because you literally defined the colors only for the typescript syntax groups in your vimrc:

```
hi! link typescriptVariableDeclaration Normal " White
hi! link TSVariable Function " Green
```

so when you switch to TypeScript you do get what you put in your vimrc.

**Comment by sainnhe** [comment]
No, the expected behavior should be keeping green, because the foreground color is controlled by tree-sitter.

That's said, the colors should always be highlighted via `TSVariable` which is green in this case, unless tree-sitter is disabled (then it will be highlighted via `typescriptVariableDeclaration` which is white in this case).

---

> This is just a syntax issue and doesn't have anything to do with vim-doge

The question is, if I uninstall vim-doge, the problem goes away, so I thought this is related to vim-doge.

**Comment by sainnhe** [comment]
I just debugged it a bit, I found that comment out one of these two lines could fix this bug:

https://github.com/kkoomen/vim-doge/blob/93a406c338f3577076b48f2c2ca9a74f2c0ebede/autoload/doge.vim#L129-L130
