### ISSUE TITLE
Add support for C#

### ISSUE THREAD

**Issue by yuhuihu** [kkoomen/vim-doge#304]
Need csharp support~~~

**Comment by John15321** [comment]
C# support would be very nice!

**Comment by kkoomen** [comment]
C# with XMLdoc has been added since [release v3.15.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.15.0)

**Comment by John15321** [comment]
Great! Thanks! 😄 

> C# with XMLdoc has been added since [release v3.15.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.15.0)
