### ISSUE TITLE
Undo resets cursor position at the top of the file

### ISSUE THREAD

**Issue by notpeelz** [kkoomen/vim-doge#309]
**Describe the bug**
Pressing `u` in normal mode after generating the documentation will reset the cursor position to the top of the file. I've only tested this with typescript files.

**To Reproduce**

- Create file `doge.vim` with:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```

- Start neovim with command: `nvim -u doge.vim`

1. Type `:set ft=typescript`
2. Enter insert mode and paste this code:
```typescript
const a = 5;  

function blah(value: number): number {
  return 4;
}
```
3. Move your cursor to the 3rd line and press `<Leader>d`
4. Press `<Escape>`
5. Press `u`

**Expected behavior**

I expected my cursor to go back to the last location before generating the documentation.

**Output of `nvim --version`**

```
NVIM v0.6.0-dev+274-g6188926e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az65-525

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by kkoomen** [comment]
Hi,

Sorry that it took almost two years, but I didn't have a lot of time and when I had time, I was improving the plugin on more important aspects. Nonetheless, I've found the problem during the v4 rewrite that has been done recently. Today is the day I found a solution to this problem that has been implemented in the upcoming version. Tests have been added to make sure this won't ever happen again in the future.

This bug has been fixed and released in [v4.4.0](https://github.com/kkoomen/vim-doge/releases/tag/v4.4.0).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.
