### ISSUE TITLE
JS doc standard generates "@return" instead of "@returns" 

### ISSUE THREAD

**Issue by notpeelz** [kkoomen/vim-doge#310]
The JSDoc doc standard generates `@return` tags instead of `@returns`.
jsdoc.app lists `@return` as a synonym for `@returns`, but TSDoc doesn't allow it.

Unfortunately this causes my eslint to complain. Would it be possible to change it to its canonical form so it doesn't completely break with TSDoc?
![image](https://user-images.githubusercontent.com/920910/136545811-9e1e9d7d-a323-4d05-b590-b3b147307a42.png)

**Comment by kkoomen** [comment]
@notpeelz Hi. Thanks for the suggestion. I do agree with your suggestion to change it to `@returns` in order to follow both standards. I have changed it in #311. After tests have passed I'll release this asap.
