### ISSUE TITLE
Python parser failed

### ISSUE THREAD

**Issue by dbatten5** [kkoomen/vim-doge#319]
**Describe the bug**

This plugin has worked very well until this morning, now whenever I run `:DogeGenerate` i get the following: 

```
[DoGe] python parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/13/k_dlm3hn6zg2sfcc19hwlqxm0000gp/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/13/k_dlm3hn6zg2sfcc19hwlqxm0000gp/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

AFAIK I haven't performed any updates to my OS or neovim since it was last working, not sure what's happened.

**Settings**

```vim
let g:doge_mapping_comment_jump_forward = ']'
let g:doge_mapping_comment_jump_backward = '['
```

**Output of `vim --version`**

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/config -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-21950-fs4dxz/neovim-0.5.0/build/include
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
```
I note there have been a few other similar issues, eg https://github.com/kkoomen/vim-doge/issues/291 but there seem to be some javascript related issues/fixes and this error is thrown from a python file.

**Comment by kkoomen** [comment]
Can you try to install node v15 (you can use nvm for this) and reinstall again? Lately issues are appearing due to the fact node v15 is required by the parser libraries. Unfortunately I don't have the time these days to maintain my project.

**Comment by kkoomen** [comment]
@dbatten5 I've done a big upgrade with all the parsers today and have published [v3.12.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.12.0).  Please upgrade locally and test whether or not you still have any issues.

**Comment by khoint0210** [comment]
hi @kkoomen 
Running the lastest one still git the same error

![CleanShot 2022-05-06 at 11 37 09](https://user-images.githubusercontent.com/12799726/167067898-7c15b4de-3134-42b4-b3ae-4123849cde22.png)

**Comment by khoint0210** [comment]
Hmmm base on the error log 
Look like missing index.js in `vim-doge` folder
So I try to remove the folder 
`/var/folders/Lt/2t_fnilx2d5_38sy7n80lLrw0000gn/T/caxa/applications/vim-doge`
Then rerun the command ` :call doge#install()`
It should work now and index.js now appear
![CleanShot 2022-05-06 at 11 50 35](https://user-images.githubusercontent.com/12799726/167069143-0a92eb53-b29b-40f6-8be3-4277ea5941b4.png)

**Comment by kkoomen** [comment]
@khoint0210 Ah yes, you did run a local build last time. You can remove the bin folder and indeed run the install command again.

So, it has been fixed?

**Comment by khoint0210** [comment]
yeah it has been fixed but @dbatten5 can you try I solution see if it work

**Comment by kkoomen** [comment]
@dbatten5 See my previous comment in order to properly confirm whether or not it works.
