### ISSUE TITLE
Inform users of Rosetta requirement for arm64 Apple Macs

### ISSUE THREAD

**Issue by jhandsel** [kkoomen/vim-doge#320]
**Is your feature request related to a problem? Please describe.**
At the moment the vim-doge MacOS binary that downloads when you run `:call doge#install()` is compiled for the x86_64 architecture. This can work on the new arm64 architecture in the latest Macbooks, but you need to have Rosetta installed first.

**Describe the solution you'd like**
Add documentation to README to remind users to run `softwareupdate --install-rosetta` on the new arm64 macbooks before installing vim-doge.

**Describe alternatives you've considered**
Also I'm happy to help by compiling a native binary for the arm64 architecture. I couldn't find any information on compiling the binary in the repo though. Please advise if this is something you'd like me to contribute:)

**Comment by kkoomen** [comment]
Hi!

This is indeed something that should be mentioned, but I wonder if it is already possible to make ARM builds. Currently we use `macos-latest` in the _Release_ workflow which defaults to MacOS 10.15. Perhaps we can try to create builds through `arch -arm64 bash <cmd>` but I haven't tested that yet, nor do I know if we should support ARM or not.

Do you have any suggestions?

**Comment by jhandsel** [comment]
I think it's worth making an ARM build, as the new macs are getting more popular and rosetta isn't installed by default. Then you could use `uname -m` in the install script to decide which binary to download and install.

**Comment by sam-mfb** [comment]
I support adding an arm build.  One problem with using Rosetta is that if you use vim inside a docker container on an M1 mac , it will be running on an arm64 (technically, aarch64) linux build and so cannot run Rosetta.  The only way around that currently is to run an amd64 linux container on the m1 under rosetta, but that is painfully slow.

**Comment by sam-mfb** [comment]
In the meantime, for anyone else with these issues, here's a Dockerfile that will compile from source. 

```
## Vim-doge build image

FROM node:16-bullseye-slim AS vim-doge-build
RUN apt-get update
RUN apt-get install -y git vim make g++ python3
RUN git clone https://github.com/kkoomen/vim-doge.git
WORKDIR vim-doge
RUN mkdir bin
RUN npm install
RUN npm run build
```

If you build this on an m1 mac, you'll get an arm build.   Couple ways to use it after that--

1. You could add: `VOLUME /vim-doge` to the end of the Dockerfile, which will copy the contents to a volume and you can then get it from there.
2. You can use it in a subsequent Docker build with something like this:
```
COPY --chown=devuser --from=vim-doge-build /vim-doge /home/devuser/.vim/plugged/vim-doge
```
Where `devuser` is the name of the user you are running as in your docker image.  If you are running as the root user you can leave out the --chown flag.  You'll also need to adjust the paths if you are using a different plugin manager.

**Comment by kkoomen** [comment]
@sam-mfb @jhandsel I've done a big upgrade with all the parsers today and have published [v3.12.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.12.0). Locally I am using the latest build and it still works when I do run `arch -arch arm64e /bin/bash` and then open a random file to generate some documentation. I am not sure if this proves that it supports arm64, but since I do use rosetta, I can't fully confirm it. Can you two please test the latest version for arm64 and confirm whether things work or not?

Thanks in advance.

**Comment by kkoomen** [comment]
@jhandsel I've reinstalled my whole OSX and am using arm64 and the latest version works fine, so I'll close this for now. If you experience issues regarding your initial problem, feel free to comment here.

**Comment by sam-mfb** [comment]
Sorry it took me so long to get around to testing this. 

On a Linux docker container, running on an M1 mac, the installer still does not install an arm64 version, as indicated by the following error when you trying to invoke vim-doge in vim:
```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
[DoGe] typescript parser failed
[Doge] Exception: Vim(return):E491: json decode error at 'qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

`uname` reports the arch on this docker image as `aarch64`

vim-doge is installed via the following line in .vimrc: `Plug 'kkoomen/vim-doge', { 'do': { -> doge#install() } }`

building from source via the workaround in my previous comment still works fine.

**Comment by kkoomen** [comment]
> On a Linux docker container, running on an M1 mac, the installer still does not install an arm64 version, as indicated by the following error when you trying to invoke vim-doge in vim:

Wait... so you're using linux right now to test this?

**Comment by sam-mfb** [comment]
Same issue; it's still downloading an x86_64 build.  It needs one compiled for aarch64 to run on arm64 linux.  It looks to me like you only have x86_64 builds on the release page.  I'm not sure why your mac version is working, unless Rosetta is somehow still running.

**Comment by sam-mfb** [comment]
> @sam-mfb To come back to your initial question, why do you want to use vim inside a linux container on your macbook? Why not use vim on your mac? Seems very unnecessary to make a linux container just for using vim.

It's not just vim.  I use different containers for different dev environments so they have the various tooling/setup i need already setup.  So rather than needing to change my setup for different dev contexts I just launch the container I need, open vim, and code away...

**Comment by sam-mfb** [comment]
Also, FWIW, the compiling from source option works fine, so this is not a big pain point for me.  Just wanted to let you know the results of testing.
