### ISSUE TITLE
Add "doxygen_cpp_comment" doc standard for C++

### ISSUE THREAD

**Issue by r7vme** [kkoomen/vim-doge#334]
**Documentation standard**

Listed [here](https://www.doxygen.nl/manual/docblocks.html) as one of the options. Basically use `///` instead of `/* */`

Example
```
/// @brief Some function
///
/// @param some_param Description
```

**How popular is the doc standard?**

Many C++ projects use `///` instead of `/* */` style comments.

- [ ] Not popular at all
- [ ] Some people use it
- [x] Quite a lot of people use it
- [ ] It's not the most popular one, but a good alternative
- [ ] Everyone is using it

P.S.: For me lack of this doc standard was a show stopper switching from decently working [DoxygenToolkit.vim](https://github.com/vim-scripts/DoxygenToolkit.vim) to vim-doge. However, I would love to switch as support of wide variety of langages and using tree-sitter is really great.

**Comment by kkoomen** [comment]
Hi,

That's something that I should do yes. I did implement it for C to use all the varieties, but not C++. I'll implement it anytime soon.

**Comment by r7vme** [comment]
@kkoomen thanks a lot, I just tried and it worked for me!

**Comment by kkoomen** [comment]
@r7vme No problem. v3.18.0 has been released just now with this feature.
