### ISSUE TITLE
Add support for Puppet

### ISSUE THREAD

**Issue by run2cmd** [kkoomen/vim-doge#34]
Puppet docs are very simmilart ot YARD. Puppet uses something what is called [Puppet Strings](https://github.com/puppetlabs/puppet-strings), but I think best examples are [Here](#https://puppet.com/docs/puppet/5.5/puppet_strings_style.html)

Alternative would be to have different match regexp for Puppet only for YARD type.

**Comment by kkoomen** [comment]
Please edit your issue using the correct [template](https://github.com/kkoomen/vim-doge/issues/new?assignees=&labels=enhancement&template=doc_standard.md&title=Add+%3Cdoc-standard%3E+doc+standard+for+%3Clanguage%3E).  After that I'm happy to help you.

**Comment by run2cmd** [comment]
Sorry. I had to use wrong template.
