### ISSUE TITLE
Error when installing via vim-plug

### ISSUE THREAD

**Issue by btrachey** [kkoomen/vim-doge#358]
**Describe the bug**

When attempting to install using the vim-plug instructions in the doc:
`Plug 'kkoomen/vim-doge', { 'do': { -> doge#install()}}`
I get an error in the output when vim-plug is trying to install:
`x Post-update hook for vim-doge ... Vim(let):E117: Unknown function: doge#helpers#deepextend`
However, if I manually run `:call doge#install()` after the `:PlugInstall`, I see the binary download, and then the plugin works as expected.

Additionally, the `->` syntax is not documented in the vim-plug docs, so I'm not sure how to try to capture the logs of the installation. 

Finally, I can see the function in `autoload/doge/helpers.vim`, so as far as I can tell the function is there to be used? Perhaps this is just a limitation of vim-plug and the installation instructions just need to be updated to say to manually run `:call doge#install()` like the instructions for pathogen/vundle, etc.?

**Output of `vim --version`**

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info

**Comment by kkoomen** [comment]
Hi. I do experience this issue as well on NVIM v0.7.0. I'll have a look.

**Comment by duguyue100** [comment]
Temporary fix:

I ran `:call doge#install()` again in neovim 0.7.0 on Ubuntu and popped out that `curl` is missing.
After I installed `curl` via `apt-get` and run `:call doge#install()` again, the installation is successful and everything is fixed.

**Comment by kkoomen** [comment]
@duguyue100 I'm sure it's not curl, because I have curl installed and am able to replicate the issue mentioned.

**Comment by duguyue100** [comment]
Yes, yes, I have a mac and it has the same problem, I guess what I was trying to say is running `:call doge#install()` again solves the problem for now.

**Comment by kkoomen** [comment]
> Yes, yes, I have a mac and it has the same problem, I guess what I was trying to say is running `:call doge#install()` again solves the problem for now.

Yes, _that_ is something I confirmed as well. That is a temporary fix, but this seems a neovim-specific issue, hence why I submitted this to neovim.
