### ISSUE TITLE
vim version

### ISSUE THREAD

**Issue by jonathaw** [kkoomen/vim-doge#36]
Hi,

looks like an awesome plugin - thanks!
I'm getting this error when trying to install:

> [DoGe] Unsupported version. Vim v8.0.1630+ is required.

but my vim version is 8.0.456.

what am I doing wrong?

thanks!

**Comment by kkoomen** [comment]
This error is self-explaining: you should update your Vim.

**Comment by kkoomen** [comment]
This error is self-explaining: you should update your Vim.
