### ISSUE TITLE
Generated javadoc has types, which according to the standard shouldn't be there

### ISSUE THREAD

**Issue by idanarye** [kkoomen/vim-doge#38]
**Describe the bug**

DoGe puts the type information of arguments and returned value in the generated javadoc - but according to the standard it shouldn't.

**To Reproduce**
1. Open a new buffer.
2. 
    ```vim
    setf java
    ```
3. Copy-paste this to the buffer:
    ```java
    public class Foo {
        public int foo(int bar) {
            return 0;
        }
    }
    ```
4. Go to the second line.
5. Run DoGe.

**Expected behavior**

DoGe should have generated a javadoc comment with only the name of the parameter in the `@param` field - the type should be omitted, as it is not part of the spec. The `@return` field should have no type either:

```java
public class Foo {
    /**
     * TODO
     * @param bar TODO
     * @return TODO
     */
    public int foo(int bar) {
        return 0;
    }
}
```

**Observed behavior**

DoGe generates the javadoc with the types of the parameter and the return value:

```java
public class Foo {
    /**
     * TODO
     * @param int bar TODO
     * @return int TODO
     */
    public int foo(int bar) {
        return 0;
    }
}
```

Note that `javadoc` considers this style erroneous, because it expects the first (and only!) argument of `@param` to be the parameter name, and interprets "int" as such:
```java
$ javadoc -quiet Foo.java
Foo.java:4: error: @param name not found
     * @param int bar TODO
              ^
Foo.java:7: warning: no @param for bar
    public int foo(int bar) {
               ^
1 error
1 warning
```

**Comment by kkoomen** [comment]
I am surprised by this. I am not a Java developer in general, but I thought it explicitly required this.

<hr />

This bug has been fixed and released in [v1.9.6](https://github.com/kkoomen/vim-doge/tree/v1.9.6).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
