### ISSUE TITLE
Generated javadoc has @return field for void methods

### ISSUE THREAD

**Issue by idanarye** [kkoomen/vim-doge#39]
**Describe the bug**
DoGe puts a `@return` fields on `void` methods - contrary to the javadoc standard.

**To Reproduce**
1. Open a new buffer.
2. 
    ```vim
    setf java
    ```
3. Copy-paste this to the buffer:
    ```java
    public class Foo {
        public void foo() {
        }
    }
    ```
4. Go to the second line.
5. Run DoGe.

**Expected behavior**

DoGe should have generated a javadoc comment without any fields:

```java
public class Foo {
    /**
     * TODO
     */
    public void foo() {
    }
}
```

**Observed behavior**

DoGe generates the javadoc with a `@return` field:

```java
public class Foo {
    /**
     * TODO
     * @return void TODO
     */
    public void foo() {
    }
}
```

Note that `javadoc` considers this style erroneous, because it does not allow `@return` fields for `void` methods.
```java
$ javadoc -quiet Foo.java
Foo.java:4: error: invalid use of @return
     * @return void TODO
       ^
1 error
```

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v1.9.5](https://github.com/kkoomen/vim-doge/tree/v1.9.5).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
