### ISSUE TITLE
Add support for c

### ISSUE THREAD

**Issue by akr-bpd** [kkoomen/vim-doge#40]
Hi, 
awesome Plugin. Support for C would be very useful.
One heavily used style is  [kernel-doc comments]( https://www.kernel.org/doc/html/latest/doc-guide/kernel-doc.html) based on Sphinx.
Alternatively  the usual doxygen-c style would be just as awesome.

Examples:

functions:

```
/**
 * foobar(): [TODO:description]
 * @arg: [TODO:description]
 *
 *  [TODO:description]
 *
 * Return: [TODO:description]
 */
int foobar(int arg)
```

structs:
```
/**
 * struct my_struct: [TODO:description]
 * @a: [TODO:description]
 * @b: [TODO:description]
 * @d: [TODO:description]
 *
 * [TODO:description]
 */
```

Thank you!

**Comment by kkoomen** [comment]
We're working on a good and stable implementation for the C-family, but we're a bit stuck at #55 using a python binding of clang. If you have any experience or want to help out, please do. At this moment we're stuck. If we fix this we can probably get a good C version running.

**Comment by kkoomen** [comment]
Development progress for C++ can be tracked via PR #56. After #56 is done, support for C will be implemented immediately after it.
