### ISSUE TITLE
[c++] @return tag  is added for functions returning void

### ISSUE THREAD

**Issue by bartlibert** [kkoomen/vim-doge#5]
**Describe the bug**
In c++ (and C), functions can have a "void" return type, meaning they don't return anything.
This plugin adds a return tag in the doxygen comments for this kind of functions though.

**To Reproduce**
Create a c++ file, for example foo.h containing:
`void foo();`

Put your cursor on the function and press "Ctrl-D"

The following comment is generated:
```
/**
 * TODO
 *
 * @return TODO
 */
```

**Expected behavior**
The "return" tag should be omitted in this case:
```
/**
 * TODO
 */
```

**Comment by kkoomen** [comment]
Thank you for submitting this issue. This issue has been fixed and merged into master in [v1.2.3](https://github.com/kkoomen/vim-doge/tree/v1.2.3).
