### ISSUE TITLE
Python parameter pep484 type annotations not being generated

### ISSUE THREAD

**Issue by RasmusJohns** [kkoomen/vim-doge#504]
**Describe the bug**

When using Python Google Docstring, the type for parameters is not automatically generated.

Consider this function from https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

```
def function_with_pep484_type_annotations(param1: int, param2: str) -> bool:
    return False
```

Using the vim-doge, we get:

```
def function_with_pep484_type_annotations(param1: int, param2: str) -> bool:
    """[TODO:summary]

    [TODO:description]

    Args:
        param1: [TODO:description]
        param2: [TODO:description]

    Returns:
        bool: [TODO:description]
    """
    return True
```

The expected result would be:

```
def function_with_pep484_type_annotations(param1: int, param2: str) -> bool:
    """[TODO:summary]

    [TODO:description]

    Args:
        param1 (int): [TODO:description]
        param2 (str): [TODO:description]

    Returns:
        bool: [TODO:description]
    """
    return True
```

**Settings**
```
let g:doge_doc_standard_python = 'google'
```

**To Reproduce**

Run vim-doge on:

```
def function_with_pep484_type_annotations(param1: int, param2: str) -> bool:
    return False
```

**Screenshots**

Not needed.

**Output of `vim --version`**

NVIM v0.7.2

**Comment by RasmusJohns** [comment]
I noticed the issue https://github.com/kkoomen/vim-doge/issues/411 and guess they are releated! Did you remove type hints from the doc strings? If so, is there now a configuration variable that you can set to enable them?

Cheers! Love the plugin.

**Comment by kkoomen** [comment]
Hi. I will have a look at this after next week. I got some other python-related issues on this project that have to be fixed. All relate to the type hints that should or should not be inside the docblock. Thanks for mentioning this, I'll have a look next week!
