### ISSUE TITLE
Support in/out parameter tags 

### ISSUE THREAD

**Issue by PlasmaHH** [kkoomen/vim-doge#533]
Doxygen supports in/out tags for parameters like

```
/**
 * \brief some function
 * \param[in] p1 first param
 * \param[out] p2 second param
 */
void some_function( int p1, int& p2 );
```
This could be activated with an option and each in/out could be a point to be cycled through with tabs. The defaults at least for C++ could depend on whether the parameter is a non-const ref or pointer.

**Comment by kkoomen** [comment]
Hi!

This is something I haven't noticed myself, but this is a good suggestion to improve overall documentation. I've implemented this for C and C++ when using doxygen. I've made it into a jumpable TODO like so:

```
/**
 * @brief [TODO:summary]
 *
 * @param[[TODO:direction]] p1 [TODO:description]
 * @param[[TODO:direction]] p2 [TODO:description]
 */
void some_function( int p1, int& p2 );
```

Side note: I see that you do use `\param`. I just resolved #534 for you as well. Thank you for making these two issues as separate issues, I appreciate it.
