### ISSUE TITLE
Support chosing of @ or \ for doxygen comments.

### ISSUE THREAD

**Issue by PlasmaHH** [kkoomen/vim-doge#534]
**Is your feature request related to a problem? Please describe.**
Some coding standards require `\param` instead of `@param` 

**Describe the solution you'd like**
A global or per type parameter to chose between `@` and `\` 

**Describe alternatives you've considered**
Changing the whole definitions of all templates. Besides being lots of work and copy/paste this would also miss on new features when updating the shipped definitions.

**Comment by kkoomen** [comment]
Hi there,

Thank you for submitting this missing feature, as I didn't notice this myself. I have implemented this and merged into master. I will do a release today somewhere and let you know here once it has been released and in which version.

**Comment by kkoomen** [comment]
This feature has been merged and released in [v3.20.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.20.0).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.

**Comment by PlasmaHH** [comment]
Very nice, works for me, thanks.
