### ISSUE TITLE
C++ comment generation is broken

### ISSUE THREAD

**Issue by AlxHnr** [kkoomen/vim-doge#55]
**Describe the bug**

The following function has only one parameter named _count_. There should be no _index_ parameter in the comment string:

```cpp
/**
 * [TODO:description]
 *
 * @param count [TODO:description]
 * @param index [TODO:description]
 */
void TestClass::printTimes(size_t count) const
{
  for(size_t index = 0; index < count; index++)
  {
    std::cout << ">>> " << index << std::endl;
  }
}
```

This function causes `:DogeGenerate` to do nothing:

```cpp
std::vector<int> TestClass::getInts(std::vector<int> vec) const
{
  return vec;
}
```

`:DogeGenerate` does nothing on special constructors:

```cpp
TestClass::TestClass(const TestClass &other)
{
  std::cout << "-- Test class copied --" << std::endl;
  this->value = other.value;
}
```

**Settings**

I used the `:DogeGenerate` command without any configuration.

**To Reproduce**

See examples in **Describe the bug**.

**Expected behavior**

Proper comment stub generation. Consider using libclang's python bindings to get precise results.

**Screenshots**

_None_, see **Describe the bug**.

**Out of `vim --version`**

`NVIM v0.3.8`

**Comment by kkoomen** [comment]
Hi.

You're providing new use-cases that haven't been taken into consideration. I will try to add them in a week or more, since I'm super busy.

> Consider using libclang's python bindings to get precise results.

What exactly do you mean with _"libclang's python bindings"_ ?

**Comment by AlxHnr** [comment]
The [Clang](https://clang.llvm.org) frontend provides a solid C and C++ parser with a [python interface](https://github.com/llvm-mirror/clang/tree/master/bindings/python). With these bindings you can pass the current file to a real compiler and query informations based on line and column numbers. E.g. you pass `main.cpp` and `line 25, column 11` to this library and it returns a tree-like data structure describing the piece of code at this location.

This would be more reliable and handle edge-cases way better than the current approach. Believe me, I've tried parsing C++ with regex and string-splitting to generate doxygen stubs ([see here](https://github.com/AlxHnr/ultisnips-snippets)). It is not very reliable and I hope one day I can get rid of my own implementation. I've been waiting for a plugin like [vim-doge](https://github.com/kkoomen/vim-doge) for a very long time because this is the feature that the Vim world needs. It seems to be the only plugin that is still being maintained and even gaining momentum.

Using libclang will add another dependency to your plugin. But it is widely available in the repositories of most mainstream Linux distributions like Ubuntu, Fedora and can be installed using a simple command. The python bindings are pretty lightweight and could even be bundled with this plugin.

**Comment by kkoomen** [comment]
I have been thinking about this approach and I know the pain of stripping C languages with pure regex. I've got multiple suggestions to use something like libclang and I prefer a pure Vim Script plugin, but I know the value that DoGe can give to others once I've implemented a solid version of this.

I'll look into the libclang and will implement support for third-party tools where needed rather then manual parsing.

**Comment by AlxHnr** [comment]
> Can you tell me why I should use the python interface? Can't I simply run clang by itself with the current file as an argument?

I don't know if the clang binary offers such functionality. The python interface gives you full access to everything.

**Comment by kkoomen** [comment]
Can you check whether this is possible without the Python interface?

**Comment by AlxHnr** [comment]
No. But I _assume_ that the clang binary provides a way to dump the syntax tree somehow, so you can parse it from vimscript. But it would probably be much more work than just using the python bindings.

**Comment by kkoomen** [comment]
I setup basic C-development docker using the clang python binding and I've been able to strip everything from a function, hooray.

Input file:
```c
void add(int m, int n) {}
void calculateMonth(int month, char* pszMonth, int buffersize) {}
```

I can now run my local script using: `./dump.py <file> <line>`, so if I run: `./dump.py file.c 1` then I get:
```
{'name': 'add', 'params': {'m': 'int', 'n': 'int'}, 'return': 'void'}
```

and if I run `./dump.py file.c 2` I get:
```
{'name': 'calculateMonth', 'params': {'month': 'int', 'pszMonth': 'char', 'buffersize': 'int'}, 'return': 'void'}
```

Unfortunately it's not able to parse functions with `::` in it. For example:
```
void Emitter::append_token(const std::string& text, const AST_Node* node) {}
```

The above is not working, but when I remove `Emitter::` it works, like so:
```
void Emitter::append_token(const std::string& text, const AST_Node* node) {}
```

Then I'm getting the following output: `{'name': 'append_token', 'params': {'text': 'const', 'node': 'const'}, 'return': 'void'}`. Do you have any idea?

**Comment by AlxHnr** [comment]
I've ran into the same issue when I tried to use libclangs python bindings a few months ago. But this is the point where I gave up, so I can't help you here.

See my python 3 script for parsing this stuff. It takes the filename, line number and column number as arguments: `./script.py foo.cpp 38 17`.

```py
#!/usr/bin/env python3

import sys
from clang.cindex import *

def getCursor(filename, line, column):
    index = Index.create()
    tu = index.parse(filename)

    file = File.from_name(tu, filename)
    location = SourceLocation.from_position(tu, file, line, column)
    return Cursor.from_location(tu, location)

print(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]))
cursor = getCursor(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]))

if cursor.kind != CursorKind.FUNCTION_DECL and \
   cursor.kind != CursorKind.CXX_METHOD:
    print("not a function: " + str(cursor.kind))
    exit()

for c in cursor.get_children():
    if c.kind == CursorKind.PARM_DECL:
        print(c.spelling)
```

Example C++ function for testing:

```cpp
void TestClass::printTimes(size_t count) const
{
  for(size_t index = 0; index < count; index++)
  {
    std::cout << ">>> " << index << std::endl;
  }
}
```

It always returns `CursorKind.NO_DECL_FOUND`, so I assume I'm not initializing libclang properly, or maybe missed some other key steps.

Unfortunately I'm not here to help you, I just don't care enough. If I would have the time, I would have implemented this already months ago.

**Comment by kkoomen** [comment]
Thanks. I'll do some research.

**Comment by kkoomen** [comment]
I find the issue. So my function declaration was the only thing in the file. The class itself with the function was not defined.

The following works:
```
class Emitter {
  public:
    void append_token();
};

void Emitter::append_token(const std::string& text, const AST_Node* node) {}
```

**Comment by kkoomen** [comment]
Update: I got a working version locally in vim-doge. After I finished the script I only had to make 2 slight adjustments to the plugin itself. Works perfectly now locally. I will push to a temporarily branch later to let you test some scenario's with me if you're okay with that. I'll let you know.

**Comment by kkoomen** [comment]
@AlxHnr Can I assume that every C / C++ developer (or other C-languages) has libclang properly installed and the binary is also in their $PATH? 

As in: if they would do:
```
$ pip3 install clang
$ python3
> from clang.cindex import Index
> Index.create() 
```

then it will detect the libclang binary properly? Because I just downloaded llvm (MacOS) and I have to use `Config.set_library_path('/Library/Developer/CommandLineTools/usr/lib/')` for now to make it work.

**Comment by AlxHnr** [comment]
> @AlxHnr Can I assume that every C / C++ developer (or other C-languages) has libclang properly installed and the binary is also in their $PATH?

No you can't. Just mention it as a dependency in the README, just like all other plugins which depend on libclang. Display a warning/error if it is not installed.

> Because I just downloaded llvm (MacOS) and I have to use Config.set_library_path('/Library/Developer/CommandLineTools/usr/lib/') for now to make it work.

You don't need to add this library path to your plugin. Configure your python environment or MacOS instead. Don't ask me how, but this is not the job of a vim plugin.

> I will push to a temporarily branch later to let you test some scenario's with me if you're okay with that.

There is a lot of C++ code out there which you can use for testing. Most compilers ship tricky C++ code as part of their test suite.

**Comment by kkoomen** [comment]
> You don't need to add this library path to your plugin. Configure your python environment or MacOS instead. Don't ask me how, but this is not the job of a vim plugin.

I had to set `LD_LIBRARY_PATH` correctly. I'll mention this later in the README.

**Comment by kkoomen** [comment]
Progress can be tracked via #56.

**Comment by kkoomen** [comment]
@AlxHnr Everything is back to how it was in the regex version, but now it's using clang. Tests are updated and it works well for the scenario's that are tested. Can you do a checkout to `feature/clang` locally and then let me know if you come across weird situations or if everything works.

If everything works as expected then I will merge #56.
