### ISSUE TITLE
New \ instead of @ causes @tparam to become param instead of \tparam

### ISSUE THREAD

**Issue by PlasmaHH** [kkoomen/vim-doge#574]
After using the feature of https://github.com/kkoomen/vim-doge/issues/534 in a fresh git pull with vim 9.0.1392 when using comment generation on C++ class templates and configuring \ for b:char I have the problem that instead of \tparam it will say <tab>param (not entirely sure about the tab here, but there are multiple spaces before param) and appearantly is interpreting \t as an escape char.

This might be because in ftplugin/cpp.vim there is the s:pattern_base dict where the string for typeParameters is being concatenated out of b:char . 'tparam ....' and then at some other place this string is re-interpreted? Interestingly that does not happen with the parameters string on the lines above it...

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v3.22.0](https://github.com/kkoomen/vim-doge/tree/v3.22.0).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.
