### ISSUE TITLE
Feature request: Google style documentation for python

### ISSUE THREAD

**Issue by yasufumy** [kkoomen/vim-doge#6]
**Documentation standard**
[This link](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings) provides the google style documentation standard.

**How popular is the doc standard?**
- [ ] Not popular at all
- [ ] Some people use it
- [x] Quite a lot of people use it
- [ ] It's not the most popular one, but a good alternative
- [ ] Everyone is using it

**Comment by kkoomen** [comment]
Hi!

Thanks for your feature request. I've implement the Google doc standard. I also found [this](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) on how to document type hints, but using my plugin and the way the comment is generated I can't give something like: ```            param2 (:obj:`int`, optional): TODO```.

I'll try to dynamically add the `optional` keyword as well. It shouldn't be a problem.

**Comment by kkoomen** [comment]
I've added support for type hints where it does a fallback to a `TODO` keyword if there is no type hint specified, so you can jump to the `TODO` item to quickly add your type hint to enhance your documentation.

I've also added the `optional` keyword when a parameter has a default value.

Tests have been written and [v1.3.0](https://github.com/kkoomen/vim-doge/tree/v1.3.0) has been released into master.

Feel free to make any other feature request or bug report for future issues. Thanks.

**Comment by yasufumy** [comment]
Thank your for your fast replay!
