### ISSUE TITLE
Add support for custom documentation

### ISSUE THREAD

**Issue by tversteeg** [kkoomen/vim-doge#60]
At my work we use a custom documentation format for Lua and C++. I would like to be able to support this.

My suggestion is to add a custom format similar to snippets.

**Comment by kkoomen** [comment]
Mhm, very interesting feature which could also improve the plugin itself, because now I'm using an array of patterns per filetype, but maybe I can use something like snippets for the base of the plugin which can be extended by the user itself.

I'll work on it.
