### ISSUE TITLE
Hyperlink exchange

### ISSUE THREAD

**Issue by Zeioth** [kkoomen/vim-doge#600]
Hello, I'm the author of [dooku.nvim](https://github.com/Zeioth/dooku.nvim), a companion plugin for vim-doge!

I've included a link to doge on the readme explaining both projects. If you include the same thing on doge's readme, it would help people to have a better experience writing documentation.

If it's not possible that's ok too!
Thank you!!

**Comment by kkoomen** [comment]
Hi. I can see where you’re coming from, as vim-doge can be used to generate the documentation and then your plugin can be used to convert it to HTML, which can be useful for internal workflows within companies I’d say.  I can add a tiny section at the bottom of my README later this week, as hyperlinks to my repository is also useful for discovery, and I think your plugin idea is somewhat useful for a specific audience.

I’ll keep you updated here whenever I’ve added the section.

**Comment by kkoomen** [comment]
This feature has been merged and released in [v4.1.1](https://github.com/kkoomen/vim-doge/releases/tag/v4.1.1).

Feel free to submit any new issues if you experience any unwanted behaviour in the future. Thanks for your contribution.
