### ISSUE TITLE
Python docstring shouldn't include cls

### ISSUE THREAD

**Issue by ObserverOfTime** [kkoomen/vim-doge#61]
**Describe the bug**
DoGe filters `self` in Python functions (#31), but not `cls`.

**To Reproduce**
1. Create a Python class.
2. Add the `__new__` method.
3. Add a `cls` argument to it.
4. Generate the docstring.

**Expected behavior**
I expected the generated docstring to not contain `cls`. Although it can often be a valid argument, it should at least be filtered in the `__new__` magic method.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/24971970/69525100-0f8eec00-0f70-11ea-8fcf-23b53253edef.png)

**Out of `vim --version`**
`NVIM v0.4.3`

**Comment by kkoomen** [comment]
@ObserverOfTime Do you know any other aliases people give to it? Then I'll cover all of them at once.

**Comment by ObserverOfTime** [comment]
I've seen some people use `klass`.

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v1.17.1](https://github.com/kkoomen/vim-doge/tree/v1.17.1).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
