### ISSUE TITLE
DogeGenerate mistakes C++ default parameters for argument name

### ISSUE THREAD

**Issue by PlasmaHH** [kkoomen/vim-doge#612]
When using default parameters in (member) functions and constructors, `DogeGenerate` will mistake the default parameter(s) for the actual parameter name, e.g.

`void foo( int x = y );`

will generate

```
/**
 * \brief [TODO:summary]
 *
 * \param[[TODO:direction]] y [TODO:description]
 */
void foo( int x = y );
```

while I would have expected `\param […] x`

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v4.3.1](https://github.com/kkoomen/vim-doge/releases/tag/v4.3.1).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
