### ISSUE TITLE
Crashing on specific function, working on others

### ISSUE THREAD

**Issue by esetnik** [kkoomen/vim-doge#621]
**Describe the bug**

Line: "    public function getDepartmentTrainingPlans(string $departmentId)"

Exception: Vim(return):E474: Expected true: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/php/parser.rs:172:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Helper output: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/php/parser.rs:172:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error detected while processing function doge#generate[31]..doge#run_parser[56]..function doge#generate[31]..doge#run_parser:
line   51:
[vim-doge] php parser failed
Press ENTER or type command to continue

**Settings**

**To Reproduce**

1. ...

**Expected behavior**

**Screenshots**

**Output of `./bin/vim-doge-helper --version`**

**Output of `vim --version`**

**Comment by kkoomen** [comment]
Hi,

Please provide me the whole class code you have so that I can have an example.

**Comment by esetnik** [comment]
Can I send privately? It's closed source.

**Comment by kkoomen** [comment]
@esetnik Sure. Mail me at koomen@pm.me

**Comment by kkoomen** [comment]
@esetnik Found the problem, even after working for so many years in PHP, I for somehow only took into account use statement usages of `use Foo\Bar;` but not `use Foo;` which resulted in an error. See #624, after tests pass, I'll do a new release. Expect a new release within an hour from now on.

**Comment by kkoomen** [comment]
Hi,

I just release v4.3.4, but through your code, I ran into another bug, so I had to do another release. Please use the new v4.3.5 and let me know if everything works as expected. I've tested lots of functions in the code you sent me, and they all generate proper documentation with v4.3.5! :) So, I don't expect anything odd to come up.

**Comment by esetnik** [comment]
I can confirm v4.3.5 is working well in that file now 👍.

Thanks for all your hard work.
