### ISSUE TITLE
Consider adding doxygen for python

### ISSUE THREAD

**Issue by PlasmaHH** [kkoomen/vim-doge#637]
**Documentation standard**
According to e.g. https://www.woolseyworkshop.com/2020/06/25/documenting-python-programs-with-doxygen/ doxygen supports its syntax in python docstrings ( where applicable ).

It's not the most popular style, but in cases where you have multiple languages, something like doxygen that supports all of them might be useful ( we started using python in such an environment and currently experimenting with doxygen support, so I can't give much examples of how it would look like )

Maybe every supported language should have a doxygen compatible documentation standard available? 

**How popular is the doc standard?**
- [ ] Not popular at all
- [x] Some people use it
- [ ] Quite a lot of people use it
- [ ] It's not the most popular one, but a good alternative
- [ ] Everyone is using it

**Comment by kkoomen** [comment]
Hi,

Doxygen is mentioned indeed online by a small subset of people who work together with some C/C++ projects, so I approve this request. I've already implemented it in #640 and will release it in the next version, which I'll do today.

**Comment by kkoomen** [comment]
This feature has been merged and released in [v4.6.0](https://github.com/kkoomen/vim-doge/releases/tag/v4.6.0).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
