### ISSUE TITLE
keymaps in lazyvim ?

### ISSUE THREAD

**Issue by Luxni** [kkoomen/vim-doge#642]
install use lazyvim :
```
return {
    "kkoomen/vim-doge",
    keys = {
        {
            "<leader>cp",
            function()
                vim.api.nvim_command("DogeGenerate")
            end,
            { desc = "doge generate" },
        },
     },
}
```
when call the 'DogeGenerate'
```
E5108: Error executing lua: /Users/lux/.config/nvim/lua/plugins/vim-doge.lua:7: function doge#generate, line 2: Vim(echoerr):[vim-doge] It seems like you forgot to set `filetype plugin on` in your .vimrc
stack traceback:
	[C]: in function 'nvim_command'
	/Users/lux/.config/nvim/lua/plugins/vim-doge.lua:7: in function </Users/lux/.config/nvim/lua/plugins/vim-doge.lua:6>
```
but when you comment keys code is working：
```
return {
	"kkoomen/vim-doge",
	-- keys = {
	--   {
	--    "<leader>cp",
	--    function()
	--	    vim.api.nvim_command("DogeGenerate")
	--    end,
	--    { desc = "doge generate" },
	--   },
	-- },
}
```
what's wrong with me?

**Comment by kkoomen** [comment]
> It seems like you forgot to set `filetype plugin on` in your .vimrc

The error message is clear here in what you should do.

**Comment by ElonH** [comment]
> > It seems like you forgot to set `filetype plugin on` in your .vimrc
> 
> The error message is clear here in what you should do.

It not working.

Plugins will be lazy-loaded, when It has `keys` key.

> https://github.com/folke/lazy.nvim?tab=readme-ov-file#lazy-loading

so I set the key `lazy = false`, It's working when `keys` exists.

doge has some problems on lazy-loaded.
