### ISSUE TITLE
Configuring vim-doge on Neovim using Lua

### ISSUE THREAD

**Issue by Omar-Ebrahim-1** [kkoomen/vim-doge#645]
Hello kkoomen,

I hope you are doing well. I have been trying to configure vim-doge, I have it working, and I want to disable the default g:doge_enable_mappings. I have tried setting to zero
```lua
vim.g.doge_enable_mappings = 0
```
and also tried nil
```lua
vim.g.doge_enable_mappings = nil
```
but neither work, and the default configuration is still enabled.

I am using lazy.nvim for my package manager and don't have .vimrc because of init.lua. My neovim configuration is [here](https://github.com/Omar-Ebrahim-1/Neovim-v2)

**Comment by kkoomen** [comment]
I personally don't use neovim, but as far as I've researched, `vim.g.doge_enable_mappings = 0` should do the trick I think. Try to add "echo g:doge_enable_mappings" here and see what it outputs.

**Comment by kkoomen** [comment]
This works:

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "

local plugins  = {
  {
    "kkoomen/vim-doge",
    run = ":call doge#install()"
  }
}

vim.g.doge_enable_mappings = 0

require("lazy").setup(plugins, {})
```
