### ISSUE TITLE
Compile-commands.json support

### ISSUE THREAD

**Issue by anstadnik** [kkoomen/vim-doge#74]
**Is your feature request related to a problem? Please describe.**

For complex C++ projects using a single parameter for compile arguments is not enough. They can be pretty big and complex or vary for different files.

**Describe the solution you'd like**

I would like to see an option for going back to the simpler regex parsing methods, or the way to use a more comprehensive way of providing the compile arguments. Now for me, the plugin does not work at all due to `[DoGe] libclang.py generator failed.` errors since I'm not providing it with compilation arguments since it's overcomplicated to write compilation arguments for every file by hand. I'd like to have at least some skeleton which I'd fill.

**Describe alternatives you've considered**

There should at least be an option for going back to the simpler regex parsing methods. The better solution, though, would be parsing the compile_commands.json which describes the arguments, using which files should be compiled. Also, I think that it might be good to add support for some LSP plugins which are capable of managing the compilation options and provide a clear description for symbols (classes, variables, etc).

**Additional context**

**Comment by kkoomen** [comment]
Hi.

C languages are not going back to regex since parsing C with regex is a hell. I'm more than happy to support compile_commands.json, but is this a common file to use? Or did you just made up this name and assumed that JSON format would probably suit it?

**Comment by anstadnik** [comment]
Hi.

No, I did not make that up :) You can read about that format more [here](https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) or [here](https://clang.llvm.org/docs/JSONCompilationDatabase.html). This is the most common way of providing info about compilation options for C/C++ files, for example, in [Language Server Protocols](https://github.com/MaskRay/ccls/wiki/Project-Setup#compile_commandsjson).
I think that it would be enough to just parse arguments from the fields `arguments` or `command`.
Though if needed, you could find a sample C++ project made with CMake, build it using the flag which I mentioned above and get an example of compile_commands.json. I did a quick search and [this](https://github.com/AlanLi7991/cmake-tutorial-sample) one worked for me (though not sure if that will work for you because of your installed libraries etc). Please let me know if you will need any help regarding this issue.

**Comment by kkoomen** [comment]
> I think that it would be enough to just parse arguments from the fields `arguments` or `command`.

A few quetions regarding this:
- Is it possible that a project contains both keys?
- Can you provide me a real-life example from both the `arguments` and `command` keys how those would look like when given to clang? I suggest you take [this example](https://sarcasm.github.io/notes/dev/compilation-database.html#what-is-a-compilation-database) as input, convert them to how clang expects these and paste it to me. Provide explanation where needed, since I know basic C/C++ but I'm far from a guru.

**Comment by anstadnik** [comment]
I am not sure, but I think it depends not on the project but on the tool which created `compile_commands.json`. I can say that I haven't seen that both keys were presented at the same time.


I would not say that I'm a guru either, but I'll try my best to help you. Speaking about [that example](https://sarcasm.github.io/notes/dev/compilation-database.html#what-is-a-compilation-database):

```
{
  "directory": "/home/user/dev/llvm/build",
  "file": "/home/user/dev/llvm/llvm/lib/Support/APFloat.cpp",
  "command": "/usr/bin/clang++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/home/user/dev/llvm/llvm/lib/Support -Iinclude -I/home/user/dev/llvm/llvm/include -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Werror=date-time -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -O3 -UNDEBUG -fno-exceptions -fno-rtti -o lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o -c /home/user/dev/llvm/llvm/lib/Support/APFloat.cpp"
}
```
The first one seems to mean that for compiling that **file** user should be in the **directory** and execute the **command**. So the command would be:
```
cd /home/user/dev/llvm/build &&
/usr/bin/clang++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/home/user/dev/llvm/llvm/lib/Support -Iinclude -I/home/user/dev/llvm/llvm/include -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Werror=date-time -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -O3 -UNDEBUG -fno-exceptions -fno-rtti -o lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o -c /home/user/dev/llvm/llvm/lib/Support/APFloat.cpp
```
---
```
{
  "directory": "/home/user/dev/llvm/build",
  "file": "/tmp/foo.cpp",
  "output": "foo.o",
  "arguments": ["/usr/bin/clang-5.0", "-xc++", "/tmp/foo.cpp", "--driver-mode=g++", "-Wall", "-I", "/home/user/dev/libcpp/libcpp/include", "-c", "--target=x86_64-unknown-linux-gnu"]
}
```
The second one means that for compiling the **file** user should be into the **directory**, execute the command, which can be made by concatenating the **arguments**, and it will produce the mentioned **output**. So:
```
cd /home/user/dev/llvm/build &&
/usr/bin/clang-5.0 -xc++ /tmp/foo.cpp --driver-mode=g++ -Wall -I /home/user/dev/libcpp/libcpp/include -c --target=x86_64-unknown-linux-gnu
```
Just to make it clear I should say that `compile_commands.json` contains the tool which compiles files, so you should not insert anything at the beginning.

While I was debugging some LSP plugins I've seen that they didn't cd into the directory, but added an addition flag `-working-directory=/some/directory` to the end of the command. I'm not sure about whether that flag works for every compiler though.

**Comment by d-karl** [comment]
I really like this idea, and I always wanted to have something like this, so I am in the process of building this. Expect a pull-request in the near future, I have most of this solved already.

**Comment by kkoomen** [comment]
Sure.

**Comment by d-karl** [comment]
Opened pull request: https://github.com/kkoomen/vim-doge/pull/78

It's far from perfect, but works reliably for generating function documentation, which is my main use case. In the worst case, it demonstrates how usage of the compile database through the python clang api is possible. Sadly, I am in no position where I am using this functionality extensively in my day to day dealings, so any further development of this will have to be a weekend project..

**Comment by kkoomen** [comment]
Closing due to new rewrite where clang is no longer needed, see #101.
