### ISSUE TITLE
example of custom template

### ISSUE THREAD

**Issue by zordsdavini** [kkoomen/vim-doge#75]
Thank you for your plugin :) It helps a lot.
Can you give example or even  better document how to add custom template. For example, in php I don't need part of [TODO:description], I need new line between paramteres and return type, and I would like to have parameters tabbed

**Comment by kkoomen** [comment]
You can use the [DogeCreateDocStandard](https://github.com/kkoomen/vim-doge#dogecreatedocstandard-doc_standard) command to start a custom doc standard or extend an existing one.

Please read [Writing your first pattern](https://github.com/kkoomen/vim-doge/blob/master/CONTRIBUTING.md#writing-your-first-pattern) and other sections below this section to know how to properly setup a pattern. It should be clear for everyone how to create a pattern by only reading the contributing document.
