### ISSUE TITLE
Add exceptions to Python function API template

### ISSUE THREAD

**Issue by scottbolte** [kkoomen/vim-doge#77]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
With python, DoGe determines a function's parameters and creates the API template accordingly. It would be great if it could also look for the `raise {exception_type}` statements in the function and use that to populate a **Raises** section.

**Describe alternatives you've considered**
Continue to do it by hand, which is tedious and error prone.

**Additional context**
See https://numpydoc.readthedocs.io/en/latest/format.html#id8 for information on how Numpy structures exception information.

**Comment by kkoomen** [comment]
Can you provide example input with expected output of what you exactly want?
