### ISSUE TITLE
Add support for C# XML documentation

### ISSUE THREAD

**Issue by levihb** [kkoomen/vim-doge#83]
**Is your feature request related to a problem? Please describe.**
Add support for C# XML documentation.

**Describe the solution you'd like**
I'd like to see the ability to generate C# XML documentation. Especially since with the open sourcing and much more relaxed licensing of .NET and C#, it has been growing in popularity on linux and macOS recently. Microsoft also plans to homogenise the ecosystem in November as well, so that all platforms are essentially equal in terms of compatibility with .NET 5

**Describe alternatives you've considered**
OmniSharp (language server for C#) can already generate some XML documentation, but it's rather limited in what it can  do. It doesn't allow the entire documentation set for a method to be generated at once, and misses out the generation of some obvious ones (e.g. returns).

**Additional context**
Microsoft's documentation is available [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/), and gives a good overview of the documenting structure.

Here are some examples of the documentation actually being used in the .NET core libraries:

https://github.com/dotnet/runtime/blob/1983518fa4c901d35bb3ac7b1f76d7fa810c3543/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableSortedSet.cs

https://github.com/dotnet/runtime/blob/3bb5f14b31213c2d148505d7af1b4bc6b09a63e9/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/ExpressionVisitor.cs

https://github.com/dotnet/runtime/blob/7a39a9e9d7352d13a78fe9948600bb30c517ee37/src/libraries/System.Private.CoreLib/src/System/Numerics/Vector3.cs

The following are just my opinions on what should be generated by default:

Namespaces don't have any docs attached to them as far as I know, or have seen.

Classes, enums, interfaces, and structs should always have \<summary\> tags, on multiple lines. If they're generics then they should have \<typeparam\> on a single line.

Enum values should have \<summary\> tags on a single line.

Properties should have a \<summary\> tag, all on a single line. There is also a \<value\> tag that explains what is being returned, but this isn't used very often (usually because it's explained in the summary), so I think it should be disabled.

Functions should have a \<summary\> tag that extends across multiple lines. They should have a \<param\> tag for each one of their parameters, on a single line. If the function returns something then it should also generate a \<returns\> tag, on one line. If the function is a generic then it should have a \<typeparam\> on a single line.

When I say across multiple lines, I mean:

```cs
/// <summary>
/// This method does xyz
/// </summary>
public void xyz()
```

Whereas on one line I mean:

```cs
/// <summary> This method does xyz </summary>
public void xyz()
```

**Comment by kkoomen** [comment]
Hi,

Thanks for the proper explanation and given details. I am a bit busy recently, so I might not have a lot of time.

Some favors I'd like to ask from you:

- Can you provide example scenarios? You can  have a look at the [playground](https://github.com/kkoomen/vim-doge/tree/master/playground) folder to get an idea. I'd like to see examples of a function with the expected doc block with it. I'll do the rest then.
- Do you perhaps know if clang can be used with C# ? if so, this makes things super easy for me, since we use clang with C and C++ in vim-doge as well.

**Comment by MrVizious** [comment]
Hi, has there been any development regarding this?

**Comment by kkoomen** [comment]
@MrVizious If you can answer the above questions in [this](https://github.com/kkoomen/vim-doge/issues/83#issuecomment-614621011) comment then I'd be happy to add support for this.

**Comment by kkoomen** [comment]
This has been added in [release v3.15.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.15.0)
