### ISSUE TITLE
Python DogeGenerate documentation indentation

### ISSUE THREAD

**Issue by samkatt** [kkoomen/vim-doge#85]
**Describe the bug**

`DogeGenerate` does not adapt to function indentation when next line is empty in python.

Calling `:DogeGenerate` on a function will generate the (correct) string documentation with (sometimes incorrect) zero indentation. This seems to only happen if the next line is empty --- If the next line contains code with the correct indentation then Doge works as expected

**Settings**
None. Reproducible with zero modifications.

**To Reproduce**
1. Empty vimrc other than the Doge plugin 
2. Create simple python file with indented function, `test.py`:
```python
def bar():

    print('hello')
```
3. `:DogeGenerate <CR>`
4. Result:
```python
def bar():
"""
[TODO:description]

"""
    print('hello')
```

**Expected behavior**
I expect the result (instead of step 4.) to be

```python
def bar():
    """
    [TODO:description]

    """
    print('hello')
```

 
**Screenshots**

Initial situation:
![init](https://user-images.githubusercontent.com/3223726/81710835-17204f80-9441-11ea-9e04-0a4e726986c3.png)

Result:
![result](https://user-images.githubusercontent.com/3223726/81710840-17204f80-9441-11ea-86b5-4e9884d82fba.png)

Expected:
![expected](https://user-images.githubusercontent.com/3223726/81711072-40d97680-9441-11ea-8d83-0eb9f72d6418.png)

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v2.2.9](https://github.com/kkoomen/vim-doge/tree/v2.2.9).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by l00sed** [comment]
@kkoomen 
Thanks for a great plugin. I seem to be having the same issue again on the latest version.
Running `:DogeGenerate` on the given python function indents the documentation at 2 spaces rather than the expected 4.
My buffer's tw=2 ts=2, but it seems to happen when I set those to 4 as well.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/23065167/210837526-c85884a8-fd68-4226-aac3-5f255fa9b6f6.png">

**Comment by kkoomen** [comment]
@l00sed Indentation is based on `shiftwidth()` which is based on the `tabstop` variable. If you've set `ts=2` then obviously it will indent at 2. This is expected behavior.

**Comment by l00sed** [comment]
@kkoomen Yes, sorry if I was unclear, it also seems to use 2 spaces with tabstop set to 4:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/23065167/210850000-c9cbebd2-b19b-421a-8821-1e49ae7ca408.png">

**Comment by l00sed** [comment]
Ah, okay, nvm. Setting sw=4 and ts=4 fixes the issue.
