### ISSUE TITLE
Allow option to generate template to scratch buffer instead of editing ftplugin

### ISSUE THREAD

**Issue by comfortablynick** [kkoomen/vim-doge#87]
**Is your feature request related to a problem? Please describe.**
I do not have my vim/nvim files under ~/.vim, so the current command creates a file in the wrong place.

**Describe the solution you'd like**
I would like the template to be opened in a scratch buffer. I don't like the idea of a plugin editing my ftplugin files. Failing that, I would at least like to be able to customize the path.

**Comment by kkoomen** [comment]
Hi,

where do you keep your vim files then if it's not in ~/.vim? And what would be the reason for you to *not* use ~/.vim or ~/.nvim?

**Comment by comfortablynick** [comment]
I primarily use nvim; mine are located at ~/.config/nvim. That works well for me because most of my ~/.config folder is in my dotfiles repo.

**Comment by kkoomen** [comment]
What about just adding a symlink `ln -s ~/.nvim ~/.config/nvim`? This would fix your problem, right?

**Comment by comfortablynick** [comment]
Obviously I could; I guess it would be nice if DoGe could load the template in a scratch buffer and not try to edit my ftplugin files. I can't think of any other plugins that do this.

If you're interested I can send a PR with an option for it, if not feel free to close.

**Comment by kkoomen** [comment]
Actually, there's no reason to write it indeed. I only need to remove the write command and remove that is pre-created the directory path. I think that'd be okay to support.

**Comment by kkoomen** [comment]
Pushed to master. Can you test it and let me know? If so I'll do a new release.

**Comment by comfortablynick** [comment]
Thanks, great solution! Works fine when I try it.

**Comment by kkoomen** [comment]
This feature has been merged and released in [v2.4.2](https://github.com/kkoomen/vim-doge/tree/v2.4.2).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.
