### ISSUE TITLE
Wrong Java parameters created

### ISSUE THREAD

**Issue by CrunchyFlakes** [kkoomen/vim-doge#90]
Hi everyone,

I have this strange bug now for a few months and have no clue whats going on. vim-doge is not able to detect the parameters for the function and takes the "throws"-statement and some words out of the method body. I dont really know whats going on and I have the up to date version of vim-doge without any custom settings. This bug does happen everytime I try to use vim-doge. 
Maybe the screenshots are more helpful than my description.

**Settings**
No custom settings.

**To Reproduce**
Happens all the time. Just try to create documentation for a method (in Java).
Maybe only happening on my end, but (if so) can't determine why.

**Expected behavior**
Documentation with the proper parameter-names.

**Screenshots**
![before](https://user-images.githubusercontent.com/26522466/88383318-9370d080-cdaa-11ea-8d2f-1524624e319f.png)
![after](https://user-images.githubusercontent.com/26522466/88383322-953a9400-cdaa-11ea-9260-10f78856c84a.png)

**Out of `vim --version`**

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Thank you for your help
Malte Töpperwien

**Comment by kkoomen** [comment]
Hi,

This is obviously a parsing issue on our side where we didn't take into account these types of methods, so the body is looking very odd. I'll fix it this evening.

**Comment by kkoomen** [comment]
Thanks for reporting the issue. Next time don't hesitate or doubt yourself. If you doubt things, just make an issue immediately and I'll look into it.

**Comment by kkoomen** [comment]
This bug has been fixed and released in [v2.5.1](https://github.com/kkoomen/vim-doge/tree/v2.5.1).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by CrunchyFlakes** [comment]
Thank you, that was really fast :)

**Comment by kkoomen** [comment]
@CrunchyFlakes I forgot to add the description contexts to the  `@throws` tags, so I just added that. Should be all good right now.
