### ISSUE TITLE
add support for ES2015 class getters and setters

### ISSUE THREAD

**Issue by sam-mfb** [kkoomen/vim-doge#91]
Currently vim-doge does not generate comments for javascript class getters and setters in the format
`class Example {
  getX() {
//
}
...
}`

It would be nice if it generated jsdoc comments for these as, for example, described here:
[https://jsdoc.app/howto-es2015-classes.html](https://jsdoc.app/howto-es2015-classes.html
)

It appears to already handle constructors and statics just fine.

Thanks!

**Comment by kkoomen** [comment]
```js
class Example {
  /**
   * [TODO:description]
   *
   * @return {[TODO:type]} [TODO:description]
   */
  getX() {}
}
```

Works fine. What problem do you have?
