### ISSUE TITLE
Can you change the quotes from double- to single-quotes?

### ISSUE THREAD

**Issue by holmescharles** [kkoomen/vim-doge#92]
Doge uses double quotes for docstrings in python, but I prefer single quotes. Is there a way to have it work with single quotes instead?

**Comment by kkoomen** [comment]
I can make a configurable option for this later this week.

**Comment by kkoomen** [comment]
This feature has been merged and released in [v2.7.0](https://github.com/kkoomen/vim-doge/tree/v2.7.0).

Feel free to submit any new issues if you experience any unwanted behavior in the future. Thanks for your contribution.

**Comment by kkoomen** [comment]
You can check the README section on how to use single quotes: https://github.com/kkoomen/vim-doge#python

**Comment by holmescharles** [comment]
Many thanks!
