### ISSUE TITLE
Can't use vim-doge with manjaro

### ISSUE THREAD

**Issue by lbiaggi** [kkoomen/vim-doge#95]
Hi, I'm trying to setup vim doge in manjaro, can you guys help me?

![error-clang-10-manjaro](https://user-images.githubusercontent.com/5401584/91989635-20426e80-ed07-11ea-9f35-5ae9b5ab46f4.gif)
![image](https://user-images.githubusercontent.com/5401584/91989376-d48fc500-ed06-11ea-9e41-1847aac9006f.png)
Tried to set file name as suggested again the error persisted (I included Config.set_library_file("libclang.so")  in the main function inside vim-doge/generators/libclang.py, and nothing changed)

![error vim-doge](https://user-images.githubusercontent.com/5401584/91989916-757e8000-ed07-11ea-9bb4-e7430c5c7c15.gif)

Regards,
Lucas

**Comment by kkoomen** [comment]
Follow the small guide that we've provided in the README. Follow the steps and you should be good.

https://github.com/kkoomen/vim-doge#using-c--c

**Comment by lbiaggi** [comment]
Not so sure

![Peek 02-09-2020 13-18](https://user-images.githubusercontent.com/5401584/92009444-e715f880-ed1e-11ea-8250-13d424a9b335.gif)

**Comment by kkoomen** [comment]
I'll have a look at it this weekend.

**Comment by lbiaggi** [comment]
Ah oks, if you need anything, feel free to ping me.

My proposed PR fix the major problem, not sure how to handle the nvim blank line.

**Comment by kkoomen** [comment]
Please, provide me the result of `ls -l /usr/lib/` on your system.

**Comment by lbiaggi** [comment]
[ls_doge.txt](https://github.com/kkoomen/vim-doge/files/5180744/ls_doge.txt)

**Comment by kkoomen** [comment]
I should've asked for `ls -l /usr/lib | grep -i libclang` but I got my answer anyway, but the fact that clang is not working on your system is not our problem. I have zero clue, as it seems you followed the steps you provided. If you have a solution to how to get the part below to work on Manjaro, then feel free to submit a PR with updated docs.

 ```
$ python3
>>> from clang.cindex import Index
>>> Index.create()
>>> <clang.cindex.Index object at 0x1084763d0>
```

**Comment by lbiaggi** [comment]
Hum, I found the solution and had send the PR #96 to fix it, is something wrong my PR?

**Comment by kkoomen** [comment]
But *why* is `Config.set_library_file("libclang.so")` needed on Arch Linux-like systems? Our docker runs alpine linux and even there it works fine. I'll look into if we can run `Config.set_library_file("libclang.so")` by default without breaking our tests. If so, it'll fix your problem as well.

**Comment by kkoomen** [comment]
I decline it because it shouldn't be needed. We've provided everything in the README and those should work on Linux and MacOS. What's the value of `echo $LD_LIBRARY_PATH` on your system? You should set this to the folder where your `libclang.so` is. If this is `/usr/lib` the add `export LD_LIBRARY_PATH="/usr/lib/"` to your `.bash_profile` or `.bashrc`

**Comment by lbiaggi** [comment]
![image](https://user-images.githubusercontent.com/5401584/92626744-b72b9f80-f2a0-11ea-8d74-0d487ed71fc1.png)

Nothing.

**Comment by kkoomen** [comment]
> Nothing.

Well, there's your problem.
