### ISSUE TITLE
Integrate treesitter?

### ISSUE THREAD

**Issue by weilbith** [kkoomen/vim-doge#98]
Hey,
since the treesitter support has become quite mature now, I was wondering if this plugin could benefit from it. So no cumbersome regex to parse parameters etc. No matter how the code is formatted, easy extract the data needed to generate the documentation skeleton. Should heavily simplify parts of this plugin and concentrate on the actual generation part.

I would love to hear any feedback what you think about it. Thanks for reading! 🙃

**Comment by kkoomen** [comment]
Oh, I honestly didn't know about this! It'd be a magnificent upgrade! I'll test this out this weekend ASAP. Many thanks for the suggestion.

**Comment by kkoomen** [comment]
Below is a list of the languages vim-doge support and those that are supported

# Not supported

- [ ] CoffeeScript
- [ ] Scala
- [ ] Kotlin
- [ ] R

# Supported

- [x] Python
- [x] PHP
- [x] JavaScript
- [x] TypeScript
- [x] Lua
- [x] Java
- [x] Groovy
- [x] Ruby
- [x] C++
- [x] C
- [x] Shell

**Comment by kkoomen** [comment]
It seems like the C-family does not require clang. If that's the case, it'd be a major improvement already, but the treesitter needs to be as good as the current regex we have, because despite how ugly Vim-regex looks, it is is well-written as parses properly

**Comment by kkoomen** [comment]
I also just noticed that the module allows custom parsers, so perhaps I could submit those myself.

**Comment by kkoomen** [comment]
@weilbith You can follow issue #101 if you want to know when the new tree-sitter rewrite will be available

**Comment by kkoomen** [comment]
@weilbith merged #101

**Comment by weilbith** [comment]
Wow. You achieved some great work! Thanks for investing your time. Looking forward to test it. :tada:

**Comment by kkoomen** [comment]
@weilbith All because you suggested it. Many thanks!
